"""Default agent definition seed data.

Maps agents to their respective domains.
Each agent has metadata for retrieval scoring and worker configuration.

Trafikverket is split into 3 sub-agents (tåg, väg, vägväder) and
SMHI into 3 sub-agents (prognos, vatten, risk) for more precise routing.
"""

from __future__ import annotations

from typing import Any

DEFAULT_AGENT_DEFINITIONS: list[dict[str, Any]] = [
    # ── SMHI sub-agents (split for precise routing) ──
    {
        "agent_id": "väder",
        "domain_id": "väder-och-klimat",
        "label": "SMHI Väderprognos & Observationer",
        "description": (
            "Väderprognoser, snöprognoser, väderanalyser och "
            "meteorologiska observationer från SMHI."
        ),
        "keywords": [
            "väder",
            "smhi",
            "temperatur",
            "regn",
            "snö",
            "vind",
            "prognos",
            "varning",
            "nederbörd",
            "observation",
            "metfcst",
            "mesan",
        ],
        "priority": 100,
        "enabled": True,
        "prompt_key": "weather_prompt",
        "primary_namespaces": [["tools", "weather", "smhi"]],
        "fallback_namespaces": [["tools", "weather"]],
        "worker_config": {"max_concurrency": 4, "timeout_seconds": 120},
        "main_identifier": "VäderAgent",
        "core_activity": "Hämtar väderprognoser och observationer från SMHI",
        "unique_scope": "SMHI meteorologisk data — prognoser och observationer",
        "geographic_scope": "Sverige",
        "excludes": ["trafik", "statistik", "bolag"],
    },
    {
        "agent_id": "väder-vatten",
        "domain_id": "väder-och-klimat",
        "label": "SMHI Hydrologi & Oceanografi",
        "description": (
            "Hydrologiska observationer (vattenstånd, vattenföring, grundvatten) "
            "och oceanografiska mätningar (havsnivå, våghöjd, havstemperatur) från SMHI."
        ),
        "keywords": [
            "hydrologi",
            "vattenstånd",
            "vattenföring",
            "grundvatten",
            "oceanografi",
            "hav",
            "havsnivå",
            "våghöjd",
            "havstemperatur",
            "sjö",
            "vänern",
            "vättern",
            "ström",
            "salinitet",
        ],
        "priority": 100,
        "enabled": True,
        "prompt_key": "weather_prompt",
        "primary_namespaces": [["tools", "weather", "hydro"]],
        "fallback_namespaces": [["tools", "weather"]],
        "worker_config": {"max_concurrency": 4, "timeout_seconds": 120},
        "main_identifier": "VattenAgent",
        "core_activity": "Hämtar hydrologiska och oceanografiska data från SMHI",
        "unique_scope": "SMHI vatten- och havsdata",
        "geographic_scope": "Sverige",
        "excludes": ["trafik", "statistik", "bolag"],
    },
    {
        "agent_id": "väder-risk",
        "domain_id": "väder-och-klimat",
        "label": "SMHI Brandrisk & Solstrålning",
        "description": (
            "Brandriskvärden (FWI-index, prognos och analys) samt "
            "solstrålningsdata (UV, global irradians, PAR) från SMHI STRÅNG-modellen."
        ),
        "keywords": [
            "brandrisk",
            "eldningsförbud",
            "fwi",
            "brand",
            "skogsbrand",
            "solstrålning",
            "uv",
            "uv-index",
            "irradians",
            "sol",
            "solenergi",
            "par",
            "strång",
        ],
        "priority": 100,
        "enabled": True,
        "prompt_key": "weather_prompt",
        "primary_namespaces": [["tools", "weather", "risk"]],
        "fallback_namespaces": [["tools", "weather"]],
        "worker_config": {"max_concurrency": 4, "timeout_seconds": 120},
        "main_identifier": "RiskAgent",
        "core_activity": "Hämtar brandrisk och solstrålning från SMHI",
        "unique_scope": "SMHI brandrisk- och solstrålningsdata",
        "geographic_scope": "Sverige",
        "excludes": ["trafik", "statistik", "bolag"],
    },
    # ── Trafikverket sub-agents (split for precise routing) ──
    {
        "agent_id": "trafik-tag",
        "domain_id": "trafik-och-transport",
        "label": "Tågtrafik & Resplanering",
        "description": (
            "Tåginformation — förseningar, tidtabeller, stationer, inställda tåg, "
            "tågprognoser och resplanering med kollektivtrafik via Trafiklab."
        ),
        "keywords": [
            "tåg",
            "tåget",
            "tag",
            "järnväg",
            "tågförsening",
            "försening",
            "tidtabell",
            "avgång",
            "ankomst",
            "station",
            "inställd",
            "inställda",
            "resplanering",
            "kollektivtrafik",
            "buss",
            "pendeltåg",
            "trafiklab",
            "sj",
        ],
        "priority": 100,
        "enabled": True,
        "prompt_key": "trafik_prompt",
        "primary_namespaces": [["tools", "trafik", "tag"]],
        "fallback_namespaces": [["tools", "trafik"]],
        "worker_config": {"max_concurrency": 4, "timeout_seconds": 120},
        "main_identifier": "TågAgent",
        "core_activity": "Hämtar tåginformation och resplanering",
        "unique_scope": "Tågtrafik, tidtabeller och resplanering",
        "geographic_scope": "Sverige",
        "excludes": ["väder", "statistik", "bolag"],
    },
    {
        "agent_id": "trafik-vag",
        "domain_id": "trafik-och-transport",
        "label": "Vägtrafik & Trafikläge",
        "description": (
            "Väginformation — störningar, olyckor, köer, vägarbeten, vägstatus, "
            "underhåll, hastigheter, avstängningar, trafikkameror och trafikprognoser."
        ),
        "keywords": [
            "trafik",
            "trafikverket",
            "väg",
            "vägar",
            "störning",
            "olycka",
            "kö",
            "köer",
            "vägarbete",
            "vägstatus",
            "underhåll",
            "hastighet",
            "avstängning",
            "kamera",
            "trafikkamera",
            "restid",
            "trafikprognos",
            "framkomlighet",
            "e4",
            "e6",
            "motorväg",
        ],
        "priority": 100,
        "enabled": True,
        "prompt_key": "trafik_prompt",
        "primary_namespaces": [["tools", "trafik", "vag"]],
        "fallback_namespaces": [["tools", "trafik"]],
        "worker_config": {"max_concurrency": 4, "timeout_seconds": 120},
        "main_identifier": "VägAgent",
        "core_activity": "Hämtar vägtrafik, störningar och trafikläge",
        "unique_scope": "Vägtrafik, störningar, kameror och vägstatus",
        "geographic_scope": "Sverige",
        "excludes": ["väder", "statistik", "bolag"],
    },
    {
        "agent_id": "trafik-vagvader",
        "domain_id": "trafik-och-transport",
        "label": "Vägväder & Väglag",
        "description": (
            "Vägväder från Trafikverkets väderstationer — halka, isrisk, "
            "vind på broar, temperatur vid vägnätet och väglag."
        ),
        "keywords": [
            "vägväder",
            "väglag",
            "halka",
            "isrisk",
            "is",
            "vind",
            "vindby",
            "temperatur",
            "väderstation",
            "mätpunkt",
            "bro",
            "öresundsbron",
        ],
        "priority": 100,
        "enabled": True,
        "prompt_key": "trafik_prompt",
        "primary_namespaces": [["tools", "trafik", "vagvader"]],
        "fallback_namespaces": [["tools", "trafik"]],
        "worker_config": {"max_concurrency": 4, "timeout_seconds": 120},
        "main_identifier": "VägväderAgent",
        "core_activity": "Hämtar vägväder, halka och väglag",
        "unique_scope": "Trafikverkets vägväder och väglagsdata",
        "geographic_scope": "Sverige",
        "excludes": ["statistik", "bolag"],
    },
    # ── Statistik sub-agents (replaces the single "statistik" agent) ──
    {
        "agent_id": "statistik-ekonomi",
        "domain_id": "ekonomi-och-skatter",
        "label": "Ekonomisk Statistik",
        "description": (
            "Hämtar ekonomisk statistik från SCB och Kolada — BNP, KPI, "
            "inflation, handel, offentlig ekonomi, hushållsekonomi, "
            "finansmarknad."
        ),
        "keywords": [
            "ekonomi",
            "bnp",
            "kpi",
            "inflation",
            "handel",
            "nationalräkenskaper",
            "priser",
            "skattesats",
            "offentlig ekonomi",
            "hushåll",
            "finansmarknad",
            "statsbudget",
        ],
        "priority": 100,
        "enabled": True,
        "prompt_key": "statistics_prompt",
        "primary_namespaces": [
            ["tools", "statistics", "scb", "ekonomi"],
            ["tools", "statistics", "kolada", "ekonomi"],
        ],
        "fallback_namespaces": [["tools", "statistics"]],
        "worker_config": {"max_concurrency": 4, "timeout_seconds": 120},
        "main_identifier": "StatistikEkonomiAgent",
        "core_activity": "Hämtar ekonomisk statistik från SCB och Kolada",
        "unique_scope": "Svensk ekonomisk statistik",
        "geographic_scope": "Sverige",
        "excludes": ["väder", "trafik", "skapa"],
    },
    {
        "agent_id": "statistik-befolkning",
        "domain_id": "befolkning-och-demografi",
        "label": "Befolkningsstatistik",
        "description": (
            "Hämtar befolkningsstatistik från SCB — folkmängd, "
            "förändringar, födda, dödsfall, invandring och utvandring."
        ),
        "keywords": [
            "befolkning",
            "folkmängd",
            "invånare",
            "kommun",
            "län",
            "demografi",
            "födda",
            "dödsfall",
            "invandring",
            "utvandring",
            "befolkningsstatistik",
        ],
        "priority": 100,
        "enabled": True,
        "prompt_key": "statistics_prompt",
        "primary_namespaces": [
            ["tools", "statistics", "scb", "befolkning"],
        ],
        "fallback_namespaces": [["tools", "statistics"]],
        "worker_config": {"max_concurrency": 4, "timeout_seconds": 120},
        "main_identifier": "StatistikBefolkningAgent",
        "core_activity": "Hämtar befolkningsstatistik från SCB",
        "unique_scope": "Svensk befolkningsstatistik",
        "geographic_scope": "Sverige",
        "excludes": ["väder", "trafik", "skapa"],
    },
    {
        "agent_id": "statistik-arbetsmarknad",
        "domain_id": "arbetsmarknad",
        "label": "Arbetsmarknadsstatistik",
        "description": (
            "Hämtar arbetsmarknadsstatistik från SCB och Kolada — "
            "arbetslöshet, sysselsättning, löner, lönestruktur, "
            "kommunala arbetsmarknadsnyckeltal."
        ),
        "keywords": [
            "arbetsmarknad",
            "arbetslöshet",
            "sysselsättning",
            "lön",
            "löner",
            "lönestatistik",
            "lönestruktur",
            "yrke",
            "anställning",
        ],
        "priority": 100,
        "enabled": True,
        "prompt_key": "statistics_prompt",
        "primary_namespaces": [
            ["tools", "statistics", "scb", "arbetsmarknad"],
            ["tools", "statistics", "kolada", "arbetsmarknad"],
        ],
        "fallback_namespaces": [["tools", "statistics"]],
        "worker_config": {"max_concurrency": 4, "timeout_seconds": 120},
        "main_identifier": "StatistikArbetsmarknadAgent",
        "core_activity": "Hämtar arbetsmarknadsstatistik från SCB och Kolada",
        "unique_scope": "Svensk arbetsmarknadsstatistik",
        "geographic_scope": "Sverige",
        "excludes": ["väder", "trafik", "skapa"],
    },
    {
        "agent_id": "statistik-utbildning",
        "domain_id": "utbildning",
        "label": "Utbildningsstatistik",
        "description": (
            "Hämtar utbildningsstatistik från SCB och Kolada — "
            "förskola, grundskola, gymnasium, högskola, forskning, "
            "pedagogtäthet, behörighet, betyg."
        ),
        "keywords": [
            "utbildning",
            "skola",
            "förskola",
            "grundskola",
            "gymnasium",
            "högskola",
            "forskning",
            "betyg",
            "behörighet",
            "pedagogtäthet",
            "lärartäthet",
            "skolstatistik",
        ],
        "priority": 100,
        "enabled": True,
        "prompt_key": "statistics_prompt",
        "primary_namespaces": [
            ["tools", "statistics", "scb", "utbildning"],
            ["tools", "statistics", "kolada", "utbildning"],
        ],
        "fallback_namespaces": [["tools", "statistics"]],
        "worker_config": {"max_concurrency": 4, "timeout_seconds": 120},
        "main_identifier": "StatistikUtbildningAgent",
        "core_activity": "Hämtar utbildningsstatistik från SCB och Kolada",
        "unique_scope": "Svensk utbildningsstatistik",
        "geographic_scope": "Sverige",
        "excludes": ["väder", "trafik", "skapa"],
    },
    {
        "agent_id": "statistik-halsa",
        "domain_id": "hälsa-och-vård",
        "label": "Hälso- & Omsorgsstatistik",
        "description": (
            "Hämtar hälso- och omsorgsstatistik från SCB och Kolada — "
            "sjukvård, äldreomsorg, LSS, IFO, barn och unga, "
            "socialtjänst, levnadsförhållanden."
        ),
        "keywords": [
            "hälsa",
            "sjukvård",
            "äldreomsorg",
            "hemtjänst",
            "lss",
            "ifo",
            "barn och unga",
            "socialtjänst",
            "levnadsförhållanden",
            "omsorg",
            "vård",
        ],
        "priority": 100,
        "enabled": True,
        "prompt_key": "statistics_prompt",
        "primary_namespaces": [
            ["tools", "statistics", "scb", "halsa"],
            ["tools", "statistics", "kolada", "halsa"],
        ],
        "fallback_namespaces": [["tools", "statistics"]],
        "worker_config": {"max_concurrency": 4, "timeout_seconds": 120},
        "main_identifier": "StatistikHälsaAgent",
        "core_activity": "Hämtar hälso- och omsorgsstatistik från SCB och Kolada",
        "unique_scope": "Svensk hälso- och omsorgsstatistik",
        "geographic_scope": "Sverige",
        "excludes": ["väder", "trafik", "skapa"],
    },
    {
        "agent_id": "statistik-miljo",
        "domain_id": "energi-och-miljö",
        "label": "Miljö- & Energistatistik",
        "description": (
            "Hämtar miljö- och energistatistik från SCB och Kolada — "
            "utsläpp, energianvändning, klimatmål, avfall, återvinning."
        ),
        "keywords": [
            "miljö",
            "energi",
            "utsläpp",
            "klimat",
            "avfall",
            "återvinning",
            "koldioxid",
            "energianvändning",
            "miljöstatistik",
        ],
        "priority": 100,
        "enabled": True,
        "prompt_key": "statistics_prompt",
        "primary_namespaces": [
            ["tools", "statistics", "scb", "miljo"],
            ["tools", "statistics", "kolada", "miljo"],
        ],
        "fallback_namespaces": [["tools", "statistics"]],
        "worker_config": {"max_concurrency": 4, "timeout_seconds": 120},
        "main_identifier": "StatistikMiljöAgent",
        "core_activity": "Hämtar miljö- och energistatistik från SCB och Kolada",
        "unique_scope": "Svensk miljö- och energistatistik",
        "geographic_scope": "Sverige",
        "excludes": ["väder", "trafik", "skapa"],
    },
    {
        "agent_id": "statistik-fastighet",
        "domain_id": "fastighet-och-mark",
        "label": "Bostads- & Fastighetsstatistik",
        "description": (
            "Hämtar bostads- och fastighetsstatistik från SCB och Kolada — "
            "bygglov, nybyggnation, bostadsbestånd, bostadskö, hyror."
        ),
        "keywords": [
            "bostad",
            "bostäder",
            "bygglov",
            "nybyggnation",
            "bostadsbestånd",
            "hyra",
            "hyror",
            "bostadskö",
            "fastighet",
            "byggande",
        ],
        "priority": 100,
        "enabled": True,
        "prompt_key": "statistics_prompt",
        "primary_namespaces": [
            ["tools", "statistics", "scb", "fastighet"],
            ["tools", "statistics", "kolada", "fastighet"],
        ],
        "fallback_namespaces": [["tools", "statistics"]],
        "worker_config": {"max_concurrency": 4, "timeout_seconds": 120},
        "main_identifier": "StatistikFastighetAgent",
        "core_activity": "Hämtar bostads- och fastighetsstatistik från SCB och Kolada",
        "unique_scope": "Svensk bostads- och fastighetsstatistik",
        "geographic_scope": "Sverige",
        "excludes": ["väder", "trafik", "skapa"],
    },
    {
        "agent_id": "statistik-naringsliv",
        "domain_id": "näringsliv-och-bolag",
        "label": "Näringslivsstatistik",
        "description": (
            "Hämtar näringslivsstatistik från SCB — företagsstruktur, "
            "omsättning, nyföretagande, branschstatistik."
        ),
        "keywords": [
            "näringsliv",
            "företag",
            "företagsstatistik",
            "omsättning",
            "nyföretagande",
            "bransch",
            "näringsverksamhet",
        ],
        "priority": 100,
        "enabled": True,
        "prompt_key": "statistics_prompt",
        "primary_namespaces": [
            ["tools", "statistics", "scb", "naringsliv"],
        ],
        "fallback_namespaces": [["tools", "statistics"]],
        "worker_config": {"max_concurrency": 4, "timeout_seconds": 120},
        "main_identifier": "StatistikNäringslivAgent",
        "core_activity": "Hämtar näringslivsstatistik från SCB",
        "unique_scope": "Svensk näringslivsstatistik",
        "geographic_scope": "Sverige",
        "excludes": ["väder", "trafik", "skapa"],
    },
    {
        "agent_id": "statistik-samhalle",
        "domain_id": "kunskap",
        "label": "Samhällsstatistik",
        "description": (
            "Hämtar samhällsstatistik från SCB och Kolada — "
            "transport, kultur, jordbruk, ämnesövergripande nyckeltal."
        ),
        "keywords": [
            "transport",
            "transporter",
            "kultur",
            "fritid",
            "jordbruk",
            "skogsbruk",
            "statistik",
            "nyckeltal",
            "samhälle",
        ],
        "priority": 100,
        "enabled": True,
        "prompt_key": "statistics_prompt",
        "primary_namespaces": [
            ["tools", "statistics", "scb", "samhalle"],
            ["tools", "statistics", "kolada", "samhalle"],
        ],
        "fallback_namespaces": [["tools", "statistics"]],
        "worker_config": {"max_concurrency": 4, "timeout_seconds": 120},
        "main_identifier": "StatistikSamhälleAgent",
        "core_activity": "Hämtar samhällsstatistik från SCB och Kolada",
        "unique_scope": "Svensk samhällsstatistik",
        "geographic_scope": "Sverige",
        "excludes": ["väder", "trafik", "skapa"],
    },
    {
        "agent_id": "bolag",
        "domain_id": "näringsliv-och-bolag",
        "label": "Bolagsverket Data",
        "description": (
            "Hämtar bolagsinformation - organisationsnummer, styrelse, "
            "årsredovisning, företagsregistret."
        ),
        "keywords": [
            "bolag",
            "bolagsverket",
            "företag",
            "organisationsnummer",
            "styrelse",
            "årsredovisning",
            "koncern",
        ],
        "priority": 100,
        "enabled": True,
        "prompt_key": "bolag_prompt",
        "primary_namespaces": [["tools", "bolag", "bolagsverket"]],
        "fallback_namespaces": [["tools", "bolag"]],
        "worker_config": {"max_concurrency": 4, "timeout_seconds": 120},
        "main_identifier": "BolagAgent",
        "core_activity": "Hämtar bolagsinformation från Bolagsverket",
        "unique_scope": "Bolagsverkets register",
        "geographic_scope": "Sverige",
        "excludes": ["väder", "trafik", "skapa"],
    },
    {
        "agent_id": "riksdagen-dokument",
        "domain_id": "politik-och-beslut",
        "label": "Riksdagen Dokument",
        "description": (
            "Söker bland riksdagens dokument - propositioner, motioner, "
            "betänkanden, SOU, Ds, direktiv, interpellationer, frågor, "
            "riksdagsskrivelser, EU-dokument och RiR-rapporter."
        ),
        "keywords": [
            "riksdagen",
            "proposition",
            "motion",
            "utskott",
            "lag",
            "lagförslag",
            "betänkande",
            "sou",
            "utredning",
            "interpellation",
            "riksdagsskrivelse",
            "eu-dokument",
            "direktiv",
        ],
        "priority": 100,
        "enabled": True,
        "prompt_key": "riksdagen_dokument_prompt",
        "primary_namespaces": [
            ["tools", "politik", "dokument"],
            ["tools", "politik", "status"],
            ["tools", "statistics", "scb", "demokrati"],
        ],
        "fallback_namespaces": [["tools", "politik"]],
        "worker_config": {"max_concurrency": 4, "timeout_seconds": 120},
        "main_identifier": "RiksdagenDokumentAgent",
        "core_activity": "Söker riksdagsdokument och lagstiftning",
        "unique_scope": "Riksdagens dokumentarkiv",
        "geographic_scope": "Sverige",
        "excludes": ["väder", "trafik", "skapa"],
    },
    {
        "agent_id": "riksdagen-debatt",
        "domain_id": "politik-och-beslut",
        "label": "Riksdagen Debatt & Voteringar",
        "description": (
            "Söker anföranden från riksdagsdebatter, frågestunder "
            "och voteringsresultat."
        ),
        "keywords": [
            "debatt",
            "anförande",
            "tal",
            "votering",
            "omröstning",
            "röstning",
            "frågestund",
            "kammare",
            "röstresultat",
        ],
        "priority": 100,
        "enabled": True,
        "prompt_key": "riksdagen_debatt_prompt",
        "primary_namespaces": [
            ["tools", "politik", "anforanden"],
            ["tools", "politik", "voteringar"],
        ],
        "fallback_namespaces": [["tools", "politik"]],
        "worker_config": {"max_concurrency": 4, "timeout_seconds": 120},
        "main_identifier": "RiksdagenDebattAgent",
        "core_activity": "Söker debatter, anföranden och voteringar",
        "unique_scope": "Riksdagens debatt- och voteringsdata",
        "geographic_scope": "Sverige",
        "excludes": ["väder", "trafik", "skapa"],
    },
    {
        "agent_id": "riksdagen-ledamoter",
        "domain_id": "politik-och-beslut",
        "label": "Riksdagen Ledamöter & Kalender",
        "description": (
            "Söker riksdagsledamöter per parti och valkrets, "
            "samt Riksdagens kalender med debatter, utskottsmöten "
            "och andra aktiviteter."
        ),
        "keywords": [
            "ledamot",
            "ledamöter",
            "riksdagsledamot",
            "parti",
            "valkrets",
            "kalender",
            "schema",
            "möte",
            "sammanträde",
            "demokrati",
            "valdeltagande",
            "val",
        ],
        "priority": 100,
        "enabled": True,
        "prompt_key": "riksdagen_ledamoter_prompt",
        "primary_namespaces": [
            ["tools", "politik", "ledamoter"],
            ["tools", "politik", "kalender"],
            ["tools", "statistics", "kolada", "demokrati"],
        ],
        "fallback_namespaces": [["tools", "politik"]],
        "worker_config": {"max_concurrency": 4, "timeout_seconds": 120},
        "main_identifier": "RiksdagenLedamoterAgent",
        "core_activity": "Söker ledamöter och riksdagskalender",
        "unique_scope": "Riksdagens ledamöter och kalender",
        "geographic_scope": "Sverige",
        "excludes": ["väder", "trafik", "skapa"],
    },
    {
        "agent_id": "marknad",
        "domain_id": "handel-och-marknad",
        "label": "Marknadsplatser",
        "description": (
            "Söker på Blocket, Tradera och andra marknadsplatser - "
            "annonser, bilar, båtar, mc, prisjämförelse."
        ),
        "keywords": [
            "blocket",
            "tradera",
            "marknadsplats",
            "annons",
            "begagnat",
            "auktion",
            "köp",
            "sälj",
        ],
        "priority": 100,
        "enabled": True,
        "prompt_key": "marketplace_prompt",
        "primary_namespaces": [["tools", "marketplace"]],
        "fallback_namespaces": [],
        "worker_config": {"max_concurrency": 4, "timeout_seconds": 120},
        "main_identifier": "MarknadsplatsAgent",
        "core_activity": "Söker marknadsplatser och annonser",
        "unique_scope": "Blocket, Tradera och liknande tjänster",
        "geographic_scope": "Sverige",
        "excludes": ["väder", "trafik", "statistik"],
    },
    {
        "agent_id": "kunskap",
        "domain_id": "kunskap",
        "label": "Kunskapssökning",
        "description": (
            "Söker i intern kunskapsbas, dokument, Notion, Slack, "
            "GitHub och andra interna källor."
        ),
        "keywords": [
            "dokument",
            "kunskap",
            "sök",
            "search",
            "notion",
            "slack",
            "github",
            "sammanfatta",
        ],
        "priority": 300,
        "enabled": True,
        "prompt_key": "knowledge_prompt",
        "primary_namespaces": [["tools", "knowledge", "kb"]],
        "fallback_namespaces": [["tools", "knowledge"]],
        "worker_config": {"max_concurrency": 4, "timeout_seconds": 120},
        "main_identifier": "KunskapsAgent",
        "core_activity": "Söker i interna och externa kunskapskällor",
        "unique_scope": "Dokumentsökning och kunskapsbas",
        "geographic_scope": "Globalt",
        "excludes": ["skapa", "hej"],
    },
    {
        "agent_id": "webb",
        "domain_id": "kunskap",
        "label": "Webbsökning",
        "description": (
            "Söker på webben, hämtar och skrapar webbsidor, länkförhandsvisning."
        ),
        "keywords": [
            "webb",
            "webbsök",
            "google",
            "länk",
            "url",
            "nyheter",
            "scrape",
            "webbsida",
        ],
        "priority": 200,
        "enabled": True,
        "prompt_key": "browser_prompt",
        "primary_namespaces": [["tools", "web", "search"]],
        "fallback_namespaces": [["tools", "web"]],
        "worker_config": {"max_concurrency": 4, "timeout_seconds": 120},
        "main_identifier": "WebbAgent",
        "core_activity": "Söker på webben och hämtar webbsidor",
        "unique_scope": "Extern webbsökning",
        "geographic_scope": "Globalt",
        "excludes": ["skapa"],
    },
    {
        "agent_id": "kod",
        "domain_id": "skapande",
        "label": "Kodgenerering",
        "description": (
            "Genererar och kör kod i sandbox - Python, beräkningar, "
            "dataanalys, filhantering."
        ),
        "keywords": [
            "kod",
            "python",
            "script",
            "beräkning",
            "sandbox",
            "kör",
            "exekvera",
            "dataanalys",
        ],
        "priority": 200,
        "enabled": True,
        "prompt_key": "code_prompt",
        "primary_namespaces": [["tools", "code", "sandbox"]],
        "fallback_namespaces": [["tools", "code"]],
        "worker_config": {"max_concurrency": 2, "timeout_seconds": 300},
        "main_identifier": "KodAgent",
        "core_activity": "Genererar och kör kod i sandboxmiljö",
        "unique_scope": "Kodgenerering och exekvering",
        "geographic_scope": "",
        "excludes": ["sök", "väder", "trafik"],
    },
    {
        "agent_id": "kartor",
        "domain_id": "skapande",
        "label": "Kartgenerering",
        "description": "Genererar statiska kartbilder med Geoapify.",
        "keywords": [
            "karta",
            "kartbild",
            "map",
            "geoapify",
            "plats",
            "position",
            "koordinat",
        ],
        "priority": 200,
        "enabled": True,
        "prompt_key": "kartor_prompt",
        "primary_namespaces": [["tools", "map", "geoapify"]],
        "fallback_namespaces": [["tools", "map"]],
        "worker_config": {"max_concurrency": 4, "timeout_seconds": 120},
        "main_identifier": "KarterAgent",
        "core_activity": "Genererar kartbilder",
        "unique_scope": "Kartgenerering",
        "geographic_scope": "Globalt",
        "excludes": ["sök", "statistik"],
    },
    {
        "agent_id": "media",
        "domain_id": "skapande",
        "label": "Mediagenerering",
        "description": "Genererar podcast, bilder och andra mediafiler.",
        "keywords": [
            "podcast",
            "bild",
            "media",
            "generera",
            "ljud",
            "video",
            "display",
        ],
        "priority": 200,
        "enabled": True,
        "prompt_key": "media_prompt",
        "primary_namespaces": [["tools", "media"]],
        "fallback_namespaces": [],
        "worker_config": {"max_concurrency": 2, "timeout_seconds": 300},
        "main_identifier": "MediaAgent",
        "core_activity": "Genererar mediafiler som podcast och bilder",
        "unique_scope": "Mediaproduktion",
        "geographic_scope": "",
        "excludes": ["sök", "statistik"],
    },
    {
        "agent_id": "åtgärd",
        "domain_id": "skapande",
        "label": "Åtgärdsagent",
        "description": (
            "Generell skapandeagent - kör uppgifter som kräver "
            "verktygskombinationer eller komplexa arbetsflöden."
        ),
        "keywords": [
            "skapa",
            "gör",
            "åtgärd",
            "generera",
            "utför",
        ],
        "priority": 300,
        "enabled": True,
        "prompt_key": "action_prompt",
        "primary_namespaces": [["tools", "action"]],
        "fallback_namespaces": [],
        "worker_config": {"max_concurrency": 4, "timeout_seconds": 120},
        "main_identifier": "ÅtgärdAgent",
        "core_activity": "Utför generella skapandeuppgifter",
        "unique_scope": "Bred skapandefunktion",
        "geographic_scope": "",
        "excludes": ["sök"],
    },
    {
        "agent_id": "syntes",
        "domain_id": "jämförelse",
        "label": "Syntesagent",
        "description": "Sammanställer och jämför data från flera källor eller modeller.",
        "keywords": [
            "syntes",
            "jämförelse",
            "compare",
            "sammanställ",
        ],
        "priority": 100,
        "enabled": True,
        "prompt_key": "synthesis_prompt",
        "primary_namespaces": [],
        "fallback_namespaces": [],
        "worker_config": {"max_concurrency": 4, "timeout_seconds": 300},
        "main_identifier": "SyntesAgent",
        "core_activity": "Sammanställer och jämför data",
        "unique_scope": "Jämförelseanalys",
        "geographic_scope": "",
        "excludes": [],
    },
    # ── Skolverket sub-agents (split by content type) ──
    {
        "agent_id": "skolverket-kursplaner",
        "domain_id": "utbildning",
        "label": "Skolverket Kursplaner & Program",
        "description": (
            "Hämtar kursplaner, ämnesplaner, läroplaner och programdata "
            "från Skolverket — ämnen, kurser, program och läroplaner med "
            "versioner, kunskapskrav och centralt innehåll."
        ),
        "keywords": [
            "ämne",
            "ämnesplan",
            "kursplan",
            "kurs",
            "program",
            "läroplan",
            "syllabus",
            "kunskapskrav",
            "centralt innehåll",
            "examensmål",
            "syfte",
            "skolverket",
            "curriculum",
            "gymnasieprogram",
            "vidareutbildning",
            "studieväg",
        ],
        "priority": 100,
        "enabled": True,
        "prompt_key": "skolverket_prompt",
        "primary_namespaces": [
            ["tools", "skolverket", "kursplaner"],
        ],
        "fallback_namespaces": [["tools", "skolverket"]],
        "worker_config": {"max_concurrency": 4, "timeout_seconds": 120},
        "main_identifier": "SkolverketKursplanerAgent",
        "core_activity": "Hämtar kursplaner, ämnesplaner och läroplaner från Skolverket",
        "unique_scope": "Skolverkets kursplaner, ämnesplaner, program och läroplaner",
        "geographic_scope": "Sverige",
        "excludes": ["väder", "trafik", "bolag"],
    },
    {
        "agent_id": "skolverket-skolenheter",
        "domain_id": "utbildning",
        "label": "Skolverket Skolenheter",
        "description": (
            "Söker och hämtar information om skolenheter från Skolverket — "
            "skolor, adresser, kontaktuppgifter, status, utbildningstillfällen, "
            "dokument och statistik per skolenhet."
        ),
        "keywords": [
            "skola",
            "skolenhet",
            "skolor",
            "grundskola",
            "gymnasium",
            "friskola",
            "kommunal skola",
            "skolinspektionen",
            "skolenhetsregister",
            "huvudman",
            "rektor",
            "adress",
            "skolverket",
        ],
        "priority": 100,
        "enabled": True,
        "prompt_key": "skolverket_prompt",
        "primary_namespaces": [
            ["tools", "skolverket", "skolenheter"],
        ],
        "fallback_namespaces": [["tools", "skolverket"]],
        "worker_config": {"max_concurrency": 4, "timeout_seconds": 120},
        "main_identifier": "SkolverketSkolenheterAgent",
        "core_activity": "Söker och hämtar information om skolor och skolenheter",
        "unique_scope": "Skolverkets skolenhetsregister",
        "geographic_scope": "Sverige",
        "excludes": ["väder", "trafik", "bolag"],
    },
    {
        "agent_id": "skolverket-vuxenutbildning",
        "domain_id": "utbildning",
        "label": "Skolverket Vuxenutbildning & Utbildningstillfällen",
        "description": (
            "Söker vuxenutbildningar och utbildningstillfällen från Skolverket — "
            "komvux, YH, SFI, studietakt, distansutbildning, geografisk "
            "filtrering, utbildningsområden och inriktningar."
        ),
        "keywords": [
            "vuxenutbildning",
            "komvux",
            "yrkeshögskola",
            "yh",
            "sfi",
            "folkhögskola",
            "distansutbildning",
            "deltid",
            "heltid",
            "studietakt",
            "utbildningstillfälle",
            "ansökan",
            "skolverket",
            "kommun",
            "län",
        ],
        "priority": 100,
        "enabled": True,
        "prompt_key": "skolverket_prompt",
        "primary_namespaces": [
            ["tools", "skolverket", "vuxenutbildning"],
        ],
        "fallback_namespaces": [["tools", "skolverket"]],
        "worker_config": {"max_concurrency": 4, "timeout_seconds": 120},
        "main_identifier": "SkolverketVuxenutbildningAgent",
        "core_activity": "Söker vuxenutbildningar och utbildningstillfällen",
        "unique_scope": "Skolverkets vuxenutbildningsregister och planerade utbildningar",
        "geographic_scope": "Sverige",
        "excludes": ["väder", "trafik", "bolag"],
    },
    {
        "agent_id": "skolverket-referens",
        "domain_id": "utbildning",
        "label": "Skolverket Referensdata & Statistik",
        "description": (
            "Hämtar referensdata, koder och statistik från Skolverket — "
            "skoltyper, ämneskoder, kurskoder, studievägskoder, nationell "
            "utbildningsstatistik och programstatistik."
        ),
        "keywords": [
            "skoltyp",
            "skolform",
            "ämneskod",
            "kurskod",
            "studieväg",
            "referensdata",
            "utbildningsstatistik",
            "nationell statistik",
            "programstatistik",
            "lärartäthet",
            "behörighet",
            "betyg",
            "skolverket",
        ],
        "priority": 100,
        "enabled": True,
        "prompt_key": "skolverket_prompt",
        "primary_namespaces": [
            ["tools", "skolverket", "referens"],
        ],
        "fallback_namespaces": [["tools", "skolverket"]],
        "worker_config": {"max_concurrency": 4, "timeout_seconds": 120},
        "main_identifier": "SkolverketReferensAgent",
        "core_activity": "Hämtar referensdata, koder och utbildningsstatistik",
        "unique_scope": "Skolverkets referensdata och nationell utbildningsstatistik",
        "geographic_scope": "Sverige",
        "excludes": ["väder", "trafik", "bolag"],
    },
]


def get_default_agent_definitions() -> dict[str, dict[str, Any]]:
    """Return default agents as a dict keyed by agent_id."""
    return {agent["agent_id"]: agent for agent in DEFAULT_AGENT_DEFINITIONS}
