"""Default agent definition seed data.

Maps agents to their respective domains.
Each agent has metadata for retrieval scoring and worker configuration.

Trafikverket is split into 3 sub-agents (tåg, väg, vägväder) and
SMHI into 3 sub-agents (prognos, vatten, risk) for more precise routing.
"""

from __future__ import annotations

from typing import Any

DEFAULT_AGENT_DEFINITIONS: list[dict[str, Any]] = [
    # ── SMHI sub-agents (split for precise routing) ──
    {
        "agent_id": "väder",
        "domain_id": "väder-och-klimat",
        "label": "SMHI Väderprognos & Observationer",
        "description": (
            "Väderprognoser, snöprognoser, väderanalyser och "
            "meteorologiska observationer från SMHI."
        ),
        "keywords": [
            "väder",
            "smhi",
            "temperatur",
            "regn",
            "snö",
            "vind",
            "prognos",
            "varning",
            "nederbörd",
            "observation",
            "metfcst",
            "mesan",
        ],
        "priority": 100,
        "enabled": True,
        "prompt_key": "weather_prompt",
        "primary_namespaces": [["tools", "weather", "smhi"]],
        "fallback_namespaces": [["tools", "weather"]],
        "worker_config": {"max_concurrency": 4, "timeout_seconds": 120},
        "main_identifier": "VäderAgent",
        "core_activity": "Hämtar väderprognoser och observationer från SMHI",
        "unique_scope": "SMHI meteorologisk data — prognoser och observationer",
        "geographic_scope": "Sverige",
        "excludes": ["trafik", "statistik", "bolag"],
    },
    {
        "agent_id": "väder-vatten",
        "domain_id": "väder-och-klimat",
        "label": "SMHI Hydrologi & Oceanografi",
        "description": (
            "Hydrologiska observationer (vattenstånd, vattenföring, grundvatten) "
            "och oceanografiska mätningar (havsnivå, våghöjd, havstemperatur) från SMHI."
        ),
        "keywords": [
            "hydrologi",
            "vattenstånd",
            "vattenföring",
            "grundvatten",
            "oceanografi",
            "hav",
            "havsnivå",
            "våghöjd",
            "havstemperatur",
            "sjö",
            "vänern",
            "vättern",
            "ström",
            "salinitet",
        ],
        "priority": 100,
        "enabled": True,
        "prompt_key": "weather_prompt",
        "primary_namespaces": [["tools", "weather", "hydro"]],
        "fallback_namespaces": [["tools", "weather"]],
        "worker_config": {"max_concurrency": 4, "timeout_seconds": 120},
        "main_identifier": "VattenAgent",
        "core_activity": "Hämtar hydrologiska och oceanografiska data från SMHI",
        "unique_scope": "SMHI vatten- och havsdata",
        "geographic_scope": "Sverige",
        "excludes": ["trafik", "statistik", "bolag"],
    },
    {
        "agent_id": "väder-risk",
        "domain_id": "väder-och-klimat",
        "label": "SMHI Brandrisk & Solstrålning",
        "description": (
            "Brandriskvärden (FWI-index, prognos och analys) samt "
            "solstrålningsdata (UV, global irradians, PAR) från SMHI STRÅNG-modellen."
        ),
        "keywords": [
            "brandrisk",
            "eldningsförbud",
            "fwi",
            "brand",
            "skogsbrand",
            "solstrålning",
            "uv",
            "uv-index",
            "irradians",
            "sol",
            "solenergi",
            "par",
            "strång",
        ],
        "priority": 100,
        "enabled": True,
        "prompt_key": "weather_prompt",
        "primary_namespaces": [["tools", "weather", "risk"]],
        "fallback_namespaces": [["tools", "weather"]],
        "worker_config": {"max_concurrency": 4, "timeout_seconds": 120},
        "main_identifier": "RiskAgent",
        "core_activity": "Hämtar brandrisk och solstrålning från SMHI",
        "unique_scope": "SMHI brandrisk- och solstrålningsdata",
        "geographic_scope": "Sverige",
        "excludes": ["trafik", "statistik", "bolag"],
    },
    # ── Trafikverket sub-agents (split for precise routing) ──
    {
        "agent_id": "trafik-tag",
        "domain_id": "trafik-och-transport",
        "label": "Tågtrafik & Resplanering",
        "description": (
            "Tåginformation — förseningar, tidtabeller, stationer, inställda tåg, "
            "tågprognoser och resplanering med kollektivtrafik via Trafiklab."
        ),
        "keywords": [
            "tåg",
            "tåget",
            "tag",
            "järnväg",
            "tågförsening",
            "försening",
            "tidtabell",
            "avgång",
            "ankomst",
            "station",
            "inställd",
            "inställda",
            "resplanering",
            "kollektivtrafik",
            "buss",
            "pendeltåg",
            "trafiklab",
            "sj",
        ],
        "priority": 100,
        "enabled": True,
        "prompt_key": "trafik_prompt",
        "primary_namespaces": [["tools", "trafik", "tag"]],
        "fallback_namespaces": [["tools", "trafik"]],
        "worker_config": {"max_concurrency": 4, "timeout_seconds": 120},
        "main_identifier": "TågAgent",
        "core_activity": "Hämtar tåginformation och resplanering",
        "unique_scope": "Tågtrafik, tidtabeller och resplanering",
        "geographic_scope": "Sverige",
        "excludes": ["väder", "statistik", "bolag"],
    },
    {
        "agent_id": "trafik-vag",
        "domain_id": "trafik-och-transport",
        "label": "Vägtrafik & Trafikläge",
        "description": (
            "Väginformation — störningar, olyckor, köer, vägarbeten, vägstatus, "
            "underhåll, hastigheter, avstängningar, trafikkameror och trafikprognoser."
        ),
        "keywords": [
            "trafik",
            "trafikverket",
            "väg",
            "vägar",
            "störning",
            "olycka",
            "kö",
            "köer",
            "vägarbete",
            "vägstatus",
            "underhåll",
            "hastighet",
            "avstängning",
            "kamera",
            "trafikkamera",
            "restid",
            "trafikprognos",
            "framkomlighet",
            "e4",
            "e6",
            "motorväg",
        ],
        "priority": 100,
        "enabled": True,
        "prompt_key": "trafik_prompt",
        "primary_namespaces": [["tools", "trafik", "vag"]],
        "fallback_namespaces": [["tools", "trafik"]],
        "worker_config": {"max_concurrency": 4, "timeout_seconds": 120},
        "main_identifier": "VägAgent",
        "core_activity": "Hämtar vägtrafik, störningar och trafikläge",
        "unique_scope": "Vägtrafik, störningar, kameror och vägstatus",
        "geographic_scope": "Sverige",
        "excludes": ["väder", "statistik", "bolag"],
    },
    {
        "agent_id": "trafik-vagvader",
        "domain_id": "trafik-och-transport",
        "label": "Vägväder & Väglag",
        "description": (
            "Vägväder från Trafikverkets väderstationer — halka, isrisk, "
            "vind på broar, temperatur vid vägnätet och väglag."
        ),
        "keywords": [
            "vägväder",
            "väglag",
            "halka",
            "isrisk",
            "is",
            "vind",
            "vindby",
            "temperatur",
            "väderstation",
            "mätpunkt",
            "bro",
            "öresundsbron",
        ],
        "priority": 100,
        "enabled": True,
        "prompt_key": "trafik_prompt",
        "primary_namespaces": [["tools", "trafik", "vagvader"]],
        "fallback_namespaces": [["tools", "trafik"]],
        "worker_config": {"max_concurrency": 4, "timeout_seconds": 120},
        "main_identifier": "VägväderAgent",
        "core_activity": "Hämtar vägväder, halka och väglag",
        "unique_scope": "Trafikverkets vägväder och väglagsdata",
        "geographic_scope": "Sverige",
        "excludes": ["statistik", "bolag"],
    },
    {
        "agent_id": "statistik",
        "domain_id": "ekonomi-och-skatter",
        "label": "SCB & Kolada Statistik",
        "description": (
            "Hämtar statistik från SCB och Kolada - befolkning, ekonomi, "
            "arbetsmarknad, utbildning, kommundata."
        ),
        "keywords": [
            "statistik",
            "scb",
            "kolada",
            "befolkning",
            "kommun",
            "ekonomi",
            "arbetsmarknad",
            "utbildning",
        ],
        "priority": 100,
        "enabled": True,
        "prompt_key": "statistics_prompt",
        "primary_namespaces": [
            ["tools", "statistics", "scb"],
            ["tools", "statistics", "kolada"],
        ],
        "fallback_namespaces": [["tools", "statistics"]],
        "worker_config": {"max_concurrency": 4, "timeout_seconds": 120},
        "main_identifier": "StatistikAgent",
        "core_activity": "Hämtar statistisk data från SCB och Kolada",
        "unique_scope": "Svensk officiell statistik",
        "geographic_scope": "Sverige",
        "excludes": ["väder", "trafik", "skapa"],
    },
    {
        "agent_id": "bolag",
        "domain_id": "näringsliv-och-bolag",
        "label": "Bolagsverket Data",
        "description": (
            "Hämtar bolagsinformation - organisationsnummer, styrelse, "
            "årsredovisning, företagsregistret."
        ),
        "keywords": [
            "bolag",
            "bolagsverket",
            "företag",
            "organisationsnummer",
            "styrelse",
            "årsredovisning",
            "koncern",
        ],
        "priority": 100,
        "enabled": True,
        "prompt_key": "bolag_prompt",
        "primary_namespaces": [["tools", "bolag", "bolagsverket"]],
        "fallback_namespaces": [["tools", "bolag"]],
        "worker_config": {"max_concurrency": 4, "timeout_seconds": 120},
        "main_identifier": "BolagAgent",
        "core_activity": "Hämtar bolagsinformation från Bolagsverket",
        "unique_scope": "Bolagsverkets register",
        "geographic_scope": "Sverige",
        "excludes": ["väder", "trafik", "skapa"],
    },
    {
        "agent_id": "riksdagen",
        "domain_id": "politik-och-beslut",
        "label": "Riksdagen Data",
        "description": (
            "Hämtar data om riksdagen - propositioner, motioner, "
            "utskottsbetänkanden, voteringar, ledamöter."
        ),
        "keywords": [
            "riksdagen",
            "proposition",
            "motion",
            "utskott",
            "votering",
            "ledamot",
            "lag",
            "lagförslag",
        ],
        "priority": 100,
        "enabled": True,
        "prompt_key": "riksdagen_prompt",
        "primary_namespaces": [["tools", "politik", "riksdagen"]],
        "fallback_namespaces": [["tools", "politik"]],
        "worker_config": {"max_concurrency": 4, "timeout_seconds": 120},
        "main_identifier": "RiksdagenAgent",
        "core_activity": "Hämtar riksdagsdata och lagstiftningsinformation",
        "unique_scope": "Riksdagens öppna data",
        "geographic_scope": "Sverige",
        "excludes": ["väder", "trafik", "skapa"],
    },
    {
        "agent_id": "marknad",
        "domain_id": "handel-och-marknad",
        "label": "Marknadsplatser",
        "description": (
            "Söker på Blocket, Tradera och andra marknadsplatser - "
            "annonser, bilar, båtar, mc, prisjämförelse."
        ),
        "keywords": [
            "blocket",
            "tradera",
            "marknadsplats",
            "annons",
            "begagnat",
            "auktion",
            "köp",
            "sälj",
        ],
        "priority": 100,
        "enabled": True,
        "prompt_key": "marketplace_prompt",
        "primary_namespaces": [["tools", "marketplace"]],
        "fallback_namespaces": [],
        "worker_config": {"max_concurrency": 4, "timeout_seconds": 120},
        "main_identifier": "MarknadsplatsAgent",
        "core_activity": "Söker marknadsplatser och annonser",
        "unique_scope": "Blocket, Tradera och liknande tjänster",
        "geographic_scope": "Sverige",
        "excludes": ["väder", "trafik", "statistik"],
    },
    {
        "agent_id": "kunskap",
        "domain_id": "kunskap",
        "label": "Kunskapssökning",
        "description": (
            "Söker i intern kunskapsbas, dokument, Notion, Slack, "
            "GitHub och andra interna källor."
        ),
        "keywords": [
            "dokument",
            "kunskap",
            "sök",
            "search",
            "notion",
            "slack",
            "github",
            "sammanfatta",
        ],
        "priority": 300,
        "enabled": True,
        "prompt_key": "knowledge_prompt",
        "primary_namespaces": [["tools", "knowledge", "kb"]],
        "fallback_namespaces": [["tools", "knowledge"]],
        "worker_config": {"max_concurrency": 4, "timeout_seconds": 120},
        "main_identifier": "KunskapsAgent",
        "core_activity": "Söker i interna och externa kunskapskällor",
        "unique_scope": "Dokumentsökning och kunskapsbas",
        "geographic_scope": "Globalt",
        "excludes": ["skapa", "hej"],
    },
    {
        "agent_id": "webb",
        "domain_id": "kunskap",
        "label": "Webbsökning",
        "description": (
            "Söker på webben, hämtar och skrapar webbsidor, länkförhandsvisning."
        ),
        "keywords": [
            "webb",
            "webbsök",
            "google",
            "länk",
            "url",
            "nyheter",
            "scrape",
            "webbsida",
        ],
        "priority": 200,
        "enabled": True,
        "prompt_key": "browser_prompt",
        "primary_namespaces": [["tools", "web", "search"]],
        "fallback_namespaces": [["tools", "web"]],
        "worker_config": {"max_concurrency": 4, "timeout_seconds": 120},
        "main_identifier": "WebbAgent",
        "core_activity": "Söker på webben och hämtar webbsidor",
        "unique_scope": "Extern webbsökning",
        "geographic_scope": "Globalt",
        "excludes": ["skapa"],
    },
    {
        "agent_id": "kod",
        "domain_id": "skapande",
        "label": "Kodgenerering",
        "description": (
            "Genererar och kör kod i sandbox - Python, beräkningar, "
            "dataanalys, filhantering."
        ),
        "keywords": [
            "kod",
            "python",
            "script",
            "beräkning",
            "sandbox",
            "kör",
            "exekvera",
            "dataanalys",
        ],
        "priority": 200,
        "enabled": True,
        "prompt_key": "code_prompt",
        "primary_namespaces": [["tools", "code", "sandbox"]],
        "fallback_namespaces": [["tools", "code"]],
        "worker_config": {"max_concurrency": 2, "timeout_seconds": 300},
        "main_identifier": "KodAgent",
        "core_activity": "Genererar och kör kod i sandboxmiljö",
        "unique_scope": "Kodgenerering och exekvering",
        "geographic_scope": "",
        "excludes": ["sök", "väder", "trafik"],
    },
    {
        "agent_id": "kartor",
        "domain_id": "skapande",
        "label": "Kartgenerering",
        "description": "Genererar statiska kartbilder med Geoapify.",
        "keywords": [
            "karta",
            "kartbild",
            "map",
            "geoapify",
            "plats",
            "position",
            "koordinat",
        ],
        "priority": 200,
        "enabled": True,
        "prompt_key": "kartor_prompt",
        "primary_namespaces": [["tools", "map", "geoapify"]],
        "fallback_namespaces": [["tools", "map"]],
        "worker_config": {"max_concurrency": 4, "timeout_seconds": 120},
        "main_identifier": "KarterAgent",
        "core_activity": "Genererar kartbilder",
        "unique_scope": "Kartgenerering",
        "geographic_scope": "Globalt",
        "excludes": ["sök", "statistik"],
    },
    {
        "agent_id": "media",
        "domain_id": "skapande",
        "label": "Mediagenerering",
        "description": "Genererar podcast, bilder och andra mediafiler.",
        "keywords": [
            "podcast",
            "bild",
            "media",
            "generera",
            "ljud",
            "video",
            "display",
        ],
        "priority": 200,
        "enabled": True,
        "prompt_key": "media_prompt",
        "primary_namespaces": [["tools", "media"]],
        "fallback_namespaces": [],
        "worker_config": {"max_concurrency": 2, "timeout_seconds": 300},
        "main_identifier": "MediaAgent",
        "core_activity": "Genererar mediafiler som podcast och bilder",
        "unique_scope": "Mediaproduktion",
        "geographic_scope": "",
        "excludes": ["sök", "statistik"],
    },
    {
        "agent_id": "åtgärd",
        "domain_id": "skapande",
        "label": "Åtgärdsagent",
        "description": (
            "Generell skapandeagent - kör uppgifter som kräver "
            "verktygskombinationer eller komplexa arbetsflöden."
        ),
        "keywords": [
            "skapa",
            "gör",
            "åtgärd",
            "generera",
            "utför",
        ],
        "priority": 300,
        "enabled": True,
        "prompt_key": "action_prompt",
        "primary_namespaces": [["tools", "action"]],
        "fallback_namespaces": [],
        "worker_config": {"max_concurrency": 4, "timeout_seconds": 120},
        "main_identifier": "ÅtgärdAgent",
        "core_activity": "Utför generella skapandeuppgifter",
        "unique_scope": "Bred skapandefunktion",
        "geographic_scope": "",
        "excludes": ["sök"],
    },
    {
        "agent_id": "syntes",
        "domain_id": "jämförelse",
        "label": "Syntesagent",
        "description": "Sammanställer och jämför data från flera källor eller modeller.",
        "keywords": [
            "syntes",
            "jämförelse",
            "compare",
            "sammanställ",
        ],
        "priority": 100,
        "enabled": True,
        "prompt_key": "synthesis_prompt",
        "primary_namespaces": [],
        "fallback_namespaces": [],
        "worker_config": {"max_concurrency": 4, "timeout_seconds": 300},
        "main_identifier": "SyntesAgent",
        "core_activity": "Sammanställer och jämför data",
        "unique_scope": "Jämförelseanalys",
        "geographic_scope": "",
        "excludes": [],
    },
]


def get_default_agent_definitions() -> dict[str, dict[str, Any]]:
    """Return default agents as a dict keyed by agent_id."""
    return {agent["agent_id"]: agent for agent in DEFAULT_AGENT_DEFINITIONS}
