"""Default agent definition seed data.

Maps the current 13 hardcoded agents to their respective domains.
Each agent has metadata for retrieval scoring and worker configuration.
"""

from __future__ import annotations

from typing import Any

DEFAULT_AGENT_DEFINITIONS: list[dict[str, Any]] = [
    {
        "agent_id": "väder",
        "domain_id": "väder-och-klimat",
        "label": "SMHI Väderdata",
        "description": (
            "Hämtar väderdata, prognoser, observationer och varningar "
            "från SMHI:s API:er (meteorologi, hydrologi, oceanografi, brandrisk)."
        ),
        "keywords": [
            "väder",
            "smhi",
            "temperatur",
            "regn",
            "snö",
            "vind",
            "prognos",
            "varning",
            "brandrisk",
            "hydrologi",
            "oceanografi",
            "nederbörd",
        ],
        "priority": 100,
        "enabled": True,
        "prompt_key": "weather_prompt",
        "primary_namespaces": [["tools", "weather", "smhi"]],
        "fallback_namespaces": [["tools", "weather"]],
        "worker_config": {"max_concurrency": 4, "timeout_seconds": 120},
        "main_identifier": "VäderAgent",
        "core_activity": "Hämtar väderdata och prognoser från SMHI",
        "unique_scope": "SMHI meteorologisk data",
        "geographic_scope": "Sverige",
        "excludes": ["trafik", "statistik", "bolag"],
    },
    {
        "agent_id": "trafik",
        "domain_id": "trafik-och-transport",
        "label": "Trafikverket Data",
        "description": (
            "Hämtar trafikinformation, störningar, väglag, "
            "järnvägsstatus och resplanering."
        ),
        "keywords": [
            "trafik",
            "trafikverket",
            "väg",
            "järnväg",
            "störning",
            "olycka",
            "väglag",
            "köer",
            "restid",
        ],
        "priority": 100,
        "enabled": True,
        "prompt_key": "trafik_prompt",
        "primary_namespaces": [["tools", "trafik", "trafikverket"]],
        "fallback_namespaces": [["tools", "trafik"]],
        "worker_config": {"max_concurrency": 4, "timeout_seconds": 120},
        "main_identifier": "TrafikAgent",
        "core_activity": "Hämtar trafikdata och störningar",
        "unique_scope": "Trafikverkets realtidsdata",
        "geographic_scope": "Sverige",
        "excludes": ["väder", "statistik", "bolag"],
    },
    {
        "agent_id": "statistik",
        "domain_id": "ekonomi-och-skatter",
        "label": "SCB & Kolada Statistik",
        "description": (
            "Hämtar statistik från SCB och Kolada - befolkning, ekonomi, "
            "arbetsmarknad, utbildning, kommundata."
        ),
        "keywords": [
            "statistik",
            "scb",
            "kolada",
            "befolkning",
            "kommun",
            "ekonomi",
            "arbetsmarknad",
            "utbildning",
        ],
        "priority": 100,
        "enabled": True,
        "prompt_key": "statistics_prompt",
        "primary_namespaces": [
            ["tools", "statistics", "scb"],
            ["tools", "statistics", "kolada"],
        ],
        "fallback_namespaces": [["tools", "statistics"]],
        "worker_config": {"max_concurrency": 4, "timeout_seconds": 120},
        "main_identifier": "StatistikAgent",
        "core_activity": "Hämtar statistisk data från SCB och Kolada",
        "unique_scope": "Svensk officiell statistik",
        "geographic_scope": "Sverige",
        "excludes": ["väder", "trafik", "skapa"],
    },
    {
        "agent_id": "bolag",
        "domain_id": "näringsliv-och-bolag",
        "label": "Bolagsverket Data",
        "description": (
            "Hämtar bolagsinformation - organisationsnummer, styrelse, "
            "årsredovisning, företagsregistret."
        ),
        "keywords": [
            "bolag",
            "bolagsverket",
            "företag",
            "organisationsnummer",
            "styrelse",
            "årsredovisning",
            "koncern",
        ],
        "priority": 100,
        "enabled": True,
        "prompt_key": "bolag_prompt",
        "primary_namespaces": [["tools", "bolag", "bolagsverket"]],
        "fallback_namespaces": [["tools", "bolag"]],
        "worker_config": {"max_concurrency": 4, "timeout_seconds": 120},
        "main_identifier": "BolagAgent",
        "core_activity": "Hämtar bolagsinformation från Bolagsverket",
        "unique_scope": "Bolagsverkets register",
        "geographic_scope": "Sverige",
        "excludes": ["väder", "trafik", "skapa"],
    },
    {
        "agent_id": "riksdagen",
        "domain_id": "politik-och-beslut",
        "label": "Riksdagen Data",
        "description": (
            "Hämtar data om riksdagen - propositioner, motioner, "
            "utskottsbetänkanden, voteringar, ledamöter."
        ),
        "keywords": [
            "riksdagen",
            "proposition",
            "motion",
            "utskott",
            "votering",
            "ledamot",
            "lag",
            "lagförslag",
        ],
        "priority": 100,
        "enabled": True,
        "prompt_key": "riksdagen_prompt",
        "primary_namespaces": [["tools", "politik", "riksdagen"]],
        "fallback_namespaces": [["tools", "politik"]],
        "worker_config": {"max_concurrency": 4, "timeout_seconds": 120},
        "main_identifier": "RiksdagenAgent",
        "core_activity": "Hämtar riksdagsdata och lagstiftningsinformation",
        "unique_scope": "Riksdagens öppna data",
        "geographic_scope": "Sverige",
        "excludes": ["väder", "trafik", "skapa"],
    },
    {
        "agent_id": "marknad",
        "domain_id": "handel-och-marknad",
        "label": "Marknadsplatser",
        "description": (
            "Söker på Blocket, Tradera och andra marknadsplatser - "
            "annonser, bilar, båtar, mc, prisjämförelse."
        ),
        "keywords": [
            "blocket",
            "tradera",
            "marknadsplats",
            "annons",
            "begagnat",
            "auktion",
            "köp",
            "sälj",
        ],
        "priority": 100,
        "enabled": True,
        "prompt_key": "marketplace_prompt",
        "primary_namespaces": [["tools", "marketplace"]],
        "fallback_namespaces": [],
        "worker_config": {"max_concurrency": 4, "timeout_seconds": 120},
        "main_identifier": "MarknadsplatsAgent",
        "core_activity": "Söker marknadsplatser och annonser",
        "unique_scope": "Blocket, Tradera och liknande tjänster",
        "geographic_scope": "Sverige",
        "excludes": ["väder", "trafik", "statistik"],
    },
    {
        "agent_id": "kunskap",
        "domain_id": "kunskap",
        "label": "Kunskapssökning",
        "description": (
            "Söker i intern kunskapsbas, dokument, Notion, Slack, "
            "GitHub och andra interna källor."
        ),
        "keywords": [
            "dokument",
            "kunskap",
            "sök",
            "search",
            "notion",
            "slack",
            "github",
            "sammanfatta",
        ],
        "priority": 300,
        "enabled": True,
        "prompt_key": "knowledge_prompt",
        "primary_namespaces": [["tools", "knowledge", "kb"]],
        "fallback_namespaces": [["tools", "knowledge"]],
        "worker_config": {"max_concurrency": 4, "timeout_seconds": 120},
        "main_identifier": "KunskapsAgent",
        "core_activity": "Söker i interna och externa kunskapskällor",
        "unique_scope": "Dokumentsökning och kunskapsbas",
        "geographic_scope": "Globalt",
        "excludes": ["skapa", "hej"],
    },
    {
        "agent_id": "webb",
        "domain_id": "kunskap",
        "label": "Webbsökning",
        "description": (
            "Söker på webben, hämtar och skrapar webbsidor, länkförhandsvisning."
        ),
        "keywords": [
            "webb",
            "webbsök",
            "google",
            "länk",
            "url",
            "nyheter",
            "scrape",
            "webbsida",
        ],
        "priority": 200,
        "enabled": True,
        "prompt_key": "browser_prompt",
        "primary_namespaces": [["tools", "web", "search"]],
        "fallback_namespaces": [["tools", "web"]],
        "worker_config": {"max_concurrency": 4, "timeout_seconds": 120},
        "main_identifier": "WebbAgent",
        "core_activity": "Söker på webben och hämtar webbsidor",
        "unique_scope": "Extern webbsökning",
        "geographic_scope": "Globalt",
        "excludes": ["skapa"],
    },
    {
        "agent_id": "kod",
        "domain_id": "skapande",
        "label": "Kodgenerering",
        "description": (
            "Genererar och kör kod i sandbox - Python, beräkningar, "
            "dataanalys, filhantering."
        ),
        "keywords": [
            "kod",
            "python",
            "script",
            "beräkning",
            "sandbox",
            "kör",
            "exekvera",
            "dataanalys",
        ],
        "priority": 200,
        "enabled": True,
        "prompt_key": "code_prompt",
        "primary_namespaces": [["tools", "code", "sandbox"]],
        "fallback_namespaces": [["tools", "code"]],
        "worker_config": {"max_concurrency": 2, "timeout_seconds": 300},
        "main_identifier": "KodAgent",
        "core_activity": "Genererar och kör kod i sandboxmiljö",
        "unique_scope": "Kodgenerering och exekvering",
        "geographic_scope": "",
        "excludes": ["sök", "väder", "trafik"],
    },
    {
        "agent_id": "kartor",
        "domain_id": "skapande",
        "label": "Kartgenerering",
        "description": "Genererar statiska kartbilder med Geoapify.",
        "keywords": [
            "karta",
            "kartbild",
            "map",
            "geoapify",
            "plats",
            "position",
            "koordinat",
        ],
        "priority": 200,
        "enabled": True,
        "prompt_key": "kartor_prompt",
        "primary_namespaces": [["tools", "map", "geoapify"]],
        "fallback_namespaces": [["tools", "map"]],
        "worker_config": {"max_concurrency": 4, "timeout_seconds": 120},
        "main_identifier": "KarterAgent",
        "core_activity": "Genererar kartbilder",
        "unique_scope": "Kartgenerering",
        "geographic_scope": "Globalt",
        "excludes": ["sök", "statistik"],
    },
    {
        "agent_id": "media",
        "domain_id": "skapande",
        "label": "Mediagenerering",
        "description": "Genererar podcast, bilder och andra mediafiler.",
        "keywords": [
            "podcast",
            "bild",
            "media",
            "generera",
            "ljud",
            "video",
            "display",
        ],
        "priority": 200,
        "enabled": True,
        "prompt_key": "media_prompt",
        "primary_namespaces": [["tools", "media"]],
        "fallback_namespaces": [],
        "worker_config": {"max_concurrency": 2, "timeout_seconds": 300},
        "main_identifier": "MediaAgent",
        "core_activity": "Genererar mediafiler som podcast och bilder",
        "unique_scope": "Mediaproduktion",
        "geographic_scope": "",
        "excludes": ["sök", "statistik"],
    },
    {
        "agent_id": "åtgärd",
        "domain_id": "skapande",
        "label": "Åtgärdsagent",
        "description": (
            "Generell skapandeagent - kör uppgifter som kräver "
            "verktygskombinationer eller komplexa arbetsflöden."
        ),
        "keywords": [
            "skapa",
            "gör",
            "åtgärd",
            "generera",
            "utför",
        ],
        "priority": 300,
        "enabled": True,
        "prompt_key": "action_prompt",
        "primary_namespaces": [["tools", "action"]],
        "fallback_namespaces": [],
        "worker_config": {"max_concurrency": 4, "timeout_seconds": 120},
        "main_identifier": "ÅtgärdAgent",
        "core_activity": "Utför generella skapandeuppgifter",
        "unique_scope": "Bred skapandefunktion",
        "geographic_scope": "",
        "excludes": ["sök"],
    },
    {
        "agent_id": "syntes",
        "domain_id": "jämförelse",
        "label": "Syntesagent",
        "description": "Sammanställer och jämför data från flera källor eller modeller.",
        "keywords": [
            "syntes",
            "jämförelse",
            "compare",
            "sammanställ",
        ],
        "priority": 100,
        "enabled": True,
        "prompt_key": "synthesis_prompt",
        "primary_namespaces": [],
        "fallback_namespaces": [],
        "worker_config": {"max_concurrency": 4, "timeout_seconds": 300},
        "main_identifier": "SyntesAgent",
        "core_activity": "Sammanställer och jämför data",
        "unique_scope": "Jämförelseanalys",
        "geographic_scope": "",
        "excludes": [],
    },
]


def get_default_agent_definitions() -> dict[str, dict[str, Any]]:
    """Return default agents as a dict keyed by agent_id."""
    return {agent["agent_id"]: agent for agent in DEFAULT_AGENT_DEFINITIONS}
