"""Default intent domain seed data.

These are the initial ~17 domains that replace the old 4-route system.
Each domain maps to a ``fallback_route`` for backward compatibility with
the ``Route`` enum.
"""

from __future__ import annotations

from typing import Any

DEFAULT_INTENT_DOMAINS: list[dict[str, Any]] = [
    {
        "domain_id": "väder-och-klimat",
        "label": "Väder & Klimat",
        "description": (
            "Frågor om väder, temperatur, nederbörd, vind, prognoser, "
            "klimatdata, observationer och varningar från SMHI eller "
            "andra vädertjänster."
        ),
        "keywords": [
            "väder",
            "vädret",
            "vader",
            "vadret",
            "smhi",
            "temperatur",
            "regn",
            "snö",
            "vind",
            "prognos",
            "nederbörd",
            "klimat",
            "varning",
            "brandrisk",
            "hydrologi",
            "oceanografi",
        ],
        "priority": 100,
        "enabled": True,
        "fallback_route": "kunskap",
        "citations_enabled": True,
        "main_identifier": "VäderDomän",
        "core_activity": "Identifierar frågor om väder, klimat och meteorologiska data",
        "unique_scope": "Väderdata, prognoser, klimatobservationer och varningar",
        "geographic_scope": "Sverige, rikstäckande",
        "excludes": ["trafik", "statistik", "bolag", "skapa"],
    },
    {
        "domain_id": "trafik-och-transport",
        "label": "Trafik & Transport",
        "description": (
            "Frågor om trafik, vägar, järnvägar, kollektivtrafik, "
            "resplanering, störningar, olyckor och trafikinformation."
        ),
        "keywords": [
            "trafik",
            "trafiken",
            "trafikverket",
            "väg",
            "vägar",
            "järnväg",
            "tåg",
            "buss",
            "sl",
            "kollektivtrafik",
            "resväg",
            "rutt",
            "störning",
            "olycka",
            "köer",
            "restid",
            "avgång",
            "ankomst",
        ],
        "priority": 100,
        "enabled": True,
        "fallback_route": "kunskap",
        "citations_enabled": True,
        "main_identifier": "TrafikDomän",
        "core_activity": "Identifierar frågor om trafikläge, resplanering och transportstörningar",
        "unique_scope": "Realtidstrafik, resplanering och trafikstörningar",
        "geographic_scope": "Sverige, rikstäckande",
        "excludes": ["väder", "statistik", "bolag", "skapa"],
    },
    {
        "domain_id": "ekonomi-och-skatter",
        "label": "Ekonomi & Skatter",
        "description": (
            "Frågor om ekonomi, skatter, moms, deklaration, räntor, "
            "riksbanken, finansinspektionen, ekonomisk statistik, "
            "riksbankens räntor, valutakurser, prognoser."
        ),
        "keywords": [
            "ekonomi",
            "skatt",
            "skatter",
            "moms",
            "deklaration",
            "ränta",
            "riksbanken",
            "finansinspektionen",
            "inflation",
            "bnp",
            "budget",
            "statsbudget",
            "styrränta",
            "växelkurs",
            "valutakurs",
            "sek",
            "swestr",
            "stibor",
            "reporänta",
            "dagslåneränta",
            "penningpolitik",
            "valuta",
        ],
        "priority": 150,
        "enabled": True,
        "fallback_route": "kunskap",
        "citations_enabled": True,
        "main_identifier": "EkonomiDomän",
        "core_activity": "Identifierar frågor om ekonomi, skatter och finansiella data",
        "unique_scope": "Ekonomisk data, skattefrågor och finansiell statistik",
        "geographic_scope": "Sverige",
        "excludes": ["väder", "trafik", "skapa"],
    },
    {
        "domain_id": "arbetsmarknad",
        "label": "Arbetsmarknad",
        "description": (
            "Frågor om arbetsmarknad, arbetslöshet, lediga jobb, "
            "yrkesområden, arbetsförmedlingen, lönestatistik."
        ),
        "keywords": [
            "arbetsmarknad",
            "arbetslöshet",
            "jobb",
            "lediga jobb",
            "arbetsförmedlingen",
            "lön",
            "lönestatistik",
            "sysselsättning",
            "yrke",
            "anställning",
        ],
        "priority": 150,
        "enabled": True,
        "fallback_route": "kunskap",
        "citations_enabled": True,
        "main_identifier": "ArbetsmarknadDomän",
        "core_activity": "Identifierar frågor om arbetsmarknad, jobb och sysselsättning",
        "unique_scope": "Arbetsmarknadsdata och jobbstatistik",
        "geographic_scope": "Sverige",
        "excludes": ["väder", "trafik", "skapa"],
    },
    {
        "domain_id": "befolkning-och-demografi",
        "label": "Befolkning & Demografi",
        "description": (
            "Frågor om befolkningsstatistik, invånarantal, kommuner, "
            "demografisk data, SCB befolkningsdata, Kolada."
        ),
        "keywords": [
            "befolkning",
            "invånare",
            "kommun",
            "kommuner",
            "län",
            "demografi",
            "befolkningsstatistik",
            "scb",
            "kolada",
            "folkmängd",
        ],
        "priority": 150,
        "enabled": True,
        "fallback_route": "kunskap",
        "citations_enabled": True,
        "main_identifier": "BefolkningDomän",
        "core_activity": "Identifierar frågor om befolkningsdata och demografi",
        "unique_scope": "Befolkningsstatistik och kommundata",
        "geographic_scope": "Sverige",
        "excludes": ["väder", "trafik", "skapa"],
    },
    {
        "domain_id": "utbildning",
        "label": "Utbildning",
        "description": (
            "Frågor om utbildning, skolor, universitet, läroplaner, "
            "kursplaner, skolverket, betyg."
        ),
        "keywords": [
            "utbildning",
            "skola",
            "universitet",
            "läroplan",
            "kursplan",
            "skolverket",
            "betyg",
            "gymnasium",
            "grundskola",
            "högskola",
        ],
        "priority": 200,
        "enabled": True,
        "fallback_route": "kunskap",
        "citations_enabled": True,
        "main_identifier": "UtbildningDomän",
        "core_activity": "Identifierar frågor om utbildning, skolor och läroplaner",
        "unique_scope": "Utbildningsdata och skolrelaterad information",
        "geographic_scope": "Sverige",
        "excludes": ["väder", "trafik", "bolag", "skapa"],
    },
    {
        "domain_id": "näringsliv-och-bolag",
        "label": "Näringsliv & Bolag",
        "description": (
            "Frågor om bolag, företag, organisationsnummer, styrelse, "
            "årsredovisning, bolagsverket, företagsregistret."
        ),
        "keywords": [
            "bolag",
            "bolagsverket",
            "företag",
            "organisationsnummer",
            "styrelse",
            "årsredovisning",
            "koncern",
            "vd",
            "aktiebolag",
            "handelsbolag",
        ],
        "priority": 150,
        "enabled": True,
        "fallback_route": "kunskap",
        "citations_enabled": True,
        "main_identifier": "BolagDomän",
        "core_activity": "Identifierar frågor om bolag, företagsregistret och bolagsdata",
        "unique_scope": "Bolagsinformation och företagsregisterdata",
        "geographic_scope": "Sverige",
        "excludes": ["väder", "trafik", "skapa"],
    },
    {
        "domain_id": "fastighet-och-mark",
        "label": "Fastighet & Mark",
        "description": (
            "Frågor om fastigheter, mark, bostäder, hyror, "
            "lantmäteriet, bostadsmarknad, tomter."
        ),
        "keywords": [
            "fastighet",
            "bostad",
            "bostäder",
            "hus",
            "lägenhet",
            "hyra",
            "lantmäteriet",
            "tomt",
            "mark",
            "bostadsmarknad",
            "bygglov",
            "nybyggnation",
            "bostadsbestånd",
            "bostadskö",
        ],
        "priority": 200,
        "enabled": True,
        "fallback_route": "kunskap",
        "citations_enabled": True,
        "main_identifier": "FastighetDomän",
        "core_activity": "Identifierar frågor om fastigheter och bostadsmarknad",
        "unique_scope": "Fastighetsdata och bostadsmarknadsinformation",
        "geographic_scope": "Sverige",
        "excludes": ["väder", "trafik", "skapa"],
    },
    {
        "domain_id": "energi-och-miljö",
        "label": "Energi & Miljö",
        "description": (
            "Frågor om energi, el, elpriser, kärnkraft, vindkraft, "
            "miljö, utsläpp, klimatmål, naturvårdsverket, "
            "aktuella elpriser, spotpriser och elmarknadsdata."
        ),
        "keywords": [
            "energi",
            "el",
            "elpris",
            "elpriser",
            "kärnkraft",
            "vindkraft",
            "solenergi",
            "miljö",
            "utsläpp",
            "klimatmål",
            "naturvårdsverket",
            "energimyndigheten",
            "spotpris",
            "kwh",
            "elzon",
            "elområde",
            "timpris",
            "elmarknad",
            "elräkning",
            "elavtal",
        ],
        "priority": 200,
        "enabled": True,
        "fallback_route": "kunskap",
        "citations_enabled": True,
        "main_identifier": "EnergiDomän",
        "core_activity": "Identifierar frågor om energi, miljö och klimatmål",
        "unique_scope": "Energidata och miljöstatistik",
        "geographic_scope": "Sverige",
        "excludes": ["väder", "trafik", "skapa"],
    },
    {
        "domain_id": "handel-och-marknad",
        "label": "Handel & Marknad",
        "description": (
            "Frågor om marknadsplatser, köp och sälj, "
            "Blocket, Tradera, begagnat, annonser, prisjämförelse."
        ),
        "keywords": [
            "blocket",
            "tradera",
            "marknadsplats",
            "marknadsplatser",
            "begagnat",
            "begagnad",
            "annons",
            "annonser",
            "auktion",
            "köp",
            "sälj",
            "prisjämförelse",
        ],
        "priority": 100,
        "enabled": True,
        "fallback_route": "kunskap",
        "citations_enabled": True,
        "main_identifier": "HandelDomän",
        "core_activity": "Identifierar frågor om köp, sälj och marknadsplatser",
        "unique_scope": "Marknadsplatsdata, annonser och prisjämförelser",
        "geographic_scope": "Sverige",
        "excludes": ["väder", "trafik", "skapa"],
    },
    {
        "domain_id": "politik-och-beslut",
        "label": "Politik & Beslut",
        "description": (
            "Frågor om riksdagen, propositioner, motioner, "
            "utskott, lagar, politiker, voteringar."
        ),
        "keywords": [
            "riksdagen",
            "proposition",
            "motion",
            "utskott",
            "lag",
            "lagförslag",
            "politiker",
            "votering",
            "riksdagsledamot",
            "parti",
            "val",
            "demokrati",
            "valdeltagande",
            "medborgarengagemang",
            "kalender",
            "sammanträde",
            "schema",
        ],
        "priority": 150,
        "enabled": True,
        "fallback_route": "kunskap",
        "citations_enabled": True,
        "main_identifier": "PolitikDomän",
        "core_activity": "Identifierar frågor om riksdagen, lagar och politiska beslut",
        "unique_scope": "Riksdagsdata och lagstiftning",
        "geographic_scope": "Sverige",
        "excludes": ["väder", "trafik", "skapa"],
    },
    {
        "domain_id": "hälsa-och-vård",
        "label": "Hälsa & Vård",
        "description": (
            "Frågor om hälsa, sjukvård, vårdcentraler, "
            "medicin, folkhälsa, socialstyrelsen."
        ),
        "keywords": [
            "hälsa",
            "sjukvård",
            "vård",
            "vårdcentral",
            "medicin",
            "folkhälsa",
            "socialstyrelsen",
            "sjukhus",
            "läkare",
            "apotek",
            "äldreomsorg",
            "hemtjänst",
            "lss",
            "ifo",
            "socialtjänst",
        ],
        "priority": 200,
        "enabled": True,
        "fallback_route": "kunskap",
        "citations_enabled": True,
        "main_identifier": "HälsaDomän",
        "core_activity": "Identifierar frågor om hälsa och sjukvård",
        "unique_scope": "Hälsodata och sjukvårdsinformation",
        "geographic_scope": "Sverige",
        "excludes": ["väder", "trafik", "skapa"],
    },
    {
        "domain_id": "rättsväsende",
        "label": "Rättsväsende",
        "description": (
            "Frågor om rättsväsendet, domstolar, polis, brott, "
            "straff, brottsstatistik, BRÅ."
        ),
        "keywords": [
            "rättsväsende",
            "domstol",
            "polis",
            "brott",
            "straff",
            "brottsstatistik",
            "brå",
            "åklagare",
            "advokat",
            "dom",
        ],
        "priority": 200,
        "enabled": True,
        "fallback_route": "kunskap",
        "citations_enabled": True,
        "main_identifier": "RättsväsendeDomän",
        "core_activity": "Identifierar frågor om rättsväsende och brottsstatistik",
        "unique_scope": "Rättsdata och brottsstatistik",
        "geographic_scope": "Sverige",
        "excludes": ["väder", "trafik", "skapa"],
    },
    {
        "domain_id": "kunskap",
        "label": "Allmän kunskap",
        "description": (
            "Generella informationsfrågor som inte matchar en specifik "
            "domän - webssökning, dokumentsökning, internt kunskapsbas."
        ),
        "keywords": [
            "dokument",
            "sök",
            "search",
            "kunskap",
            "sammanfatta",
            "webb",
            "länk",
            "nyheter",
            "kolla",
            "vad är",
            "hur mycket",
        ],
        "priority": 400,
        "enabled": True,
        "fallback_route": "kunskap",
        "citations_enabled": True,
        "main_identifier": "KunskapFallback",
        "core_activity": "Fångar generella informationsfrågor utan specifik domäntillhörighet",
        "unique_scope": "Bred informationsinhämtning som fallback",
        "geographic_scope": "Globalt",
        "excludes": ["skapa", "hej", "tjena"],
    },
    {
        "domain_id": "skapande",
        "label": "Skapande & Produktion",
        "description": (
            "Användaren vill att systemet skapar eller genererar något - "
            "podcast, kartbilder, kod, filer, bilder."
        ),
        "keywords": [
            "skapa",
            "generera",
            "gör",
            "rita",
            "podcast",
            "bild",
            "karta",
            "kartbild",
            "kod",
            "script",
            "python",
            "sandbox",
            "fil",
            "skriv",
        ],
        "priority": 300,
        "enabled": True,
        "fallback_route": "skapande",
        "citations_enabled": False,
        "main_identifier": "SkapandeDomän",
        "core_activity": "Identifierar frågor om generering av nytt innehåll",
        "unique_scope": "Skapande och generering",
        "geographic_scope": "",
        "excludes": ["sök", "search", "vad är", "hej"],
    },
    {
        "domain_id": "konversation",
        "label": "Konversation",
        "description": "Hälsningar och enkel konversation utan verktyg.",
        "keywords": [
            "hej",
            "tjena",
            "hallå",
            "hur mår du",
            "konversation",
            "smalltalk",
        ],
        "priority": 500,
        "enabled": True,
        "fallback_route": "konversation",
        "citations_enabled": False,
        "main_identifier": "KonversationDomän",
        "core_activity": "Identifierar hälsningar och enkel konversation",
        "unique_scope": "Enbart smalltalk utan informationsbehov",
        "geographic_scope": "",
        "excludes": ["sök", "skapa", "statistik", "trafik"],
    },
    {
        "domain_id": "jämförelse",
        "label": "Jämförelse & Analys",
        "description": "Jämförelse-läge när användaren explicit efterfrågar compare.",
        "keywords": [
            "/compare",
            "compare",
            "jämför",
            "jamfor",
            "jämförelse",
        ],
        "priority": 50,
        "enabled": True,
        "fallback_route": "jämförelse",
        "citations_enabled": True,
        "main_identifier": "JämförelseDomän",
        "core_activity": "Identifierar explicita jämförelser mellan källor eller modeller",
        "unique_scope": "Enbart explicita jämförelser",
        "geographic_scope": "",
        "excludes": ["skapa", "hej", "sök"],
    },
]


def get_default_intent_domains() -> dict[str, dict[str, Any]]:
    """Return default domains as a dict keyed by domain_id."""
    return {domain["domain_id"]: domain for domain in DEFAULT_INTENT_DOMAINS}
