"""Default tool identity metadata sourced from docs/tools.yaml."""

from __future__ import annotations

from typing import Any


_DEFAULT_TOOL_IDENTITY: dict[str, dict[str, Any]] = {
    "scb_arbetsmarknad": {
        "description": "Statistik om sysselsattning, arbetsloshet och loner fran SCB.",
        "keywords": ["sysselsättning", "arbetslöshet", "arbetskraft", "löner", "AKU", "bransch", "yrke", "tidsserie", "inkomst"],
        "main_identifier": "SCB arbetsmarknadsstatistik",
        "core_activity": "sysselsättning arbetslöshet löner",
        "unique_scope": "inte kommunala åtgärder Kolada",
        "geographic_scope": "Sverige",
    },
    "scb_befolkning": {
        "description": "Befolkningsstatistik fran SCB: folkmangd, flyttningar, fodslar och dodsfall.",
        "keywords": ["folkmängd", "befolkning", "flyttningar", "födelser", "dödsfall", "ålder", "kön", "region", "kommun", "demografi"],
        "main_identifier": "SCB befolkningsstatistik",
        "core_activity": "folkmängd flyttningar födelser dödsfall",
        "unique_scope": "inte arbetsmarknad eller ekonomi",
        "geographic_scope": "kommun Sverige",
    },
    "scb_boende_byggande": {
        "description": "SCB-statistik om bostadsbestand, nybyggnation och bygglov.",
        "keywords": ["bostadsbestånd", "nybyggnation", "bygglov", "hyresrätt", "bostadsrätt", "småhus", "byggstart", "färdigställt"],
        "main_identifier": "SCB bostadsstatistik",
        "core_activity": "bostadsbestånd nybyggnation bygglov",
        "unique_scope": "inte kommunala hyror eller köer Kolada",
        "geographic_scope": "Sverige",
    },
    "scb_demokrati": {
        "description": "SCB-statistik om valdeltagande och medborgarengagemang.",
        "keywords": ["valdeltagande", "medborgarengagemang", "förtroende", "e-tjänster", "medborgardialog"],
        "main_identifier": "SCB demokratistatistik",
        "core_activity": "valdeltagande medborgarengagemang",
        "unique_scope": "inte kommunal nöjdhet Kolada",
        "geographic_scope": "Sverige",
    },
    "scb_energi": {
        "description": "SCB-statistik om energianvandning och elproduktion.",
        "keywords": ["energianvändning", "elproduktion", "förbrukning", "per", "invånare", "hushåll", "bransch"],
        "main_identifier": "SCB energistatistik",
        "core_activity": "energianvändning elproduktion",
        "unique_scope": "inte kommunal energi Kolada",
        "geographic_scope": "Sverige",
    },
    "scb_finansmarknad": {
        "description": "SCB-statistik om rantor, lan och bostadslan.",
        "keywords": ["räntor", "lån", "bostadslån", "sparande", "investeringar"],
        "main_identifier": "SCB finansmarknadsstatistik",
        "core_activity": "räntor lån bostadslån",
        "unique_scope": "inte kommunal budget Kolada",
        "geographic_scope": "Sverige",
    },
    "scb_handel": {
        "description": "SCB-statistik om export, import och handelsbalans.",
        "keywords": ["export", "import", "handelsbalans", "varuhandel", "tjänstehandel", "land"],
        "main_identifier": "SCB handelsstatistik",
        "core_activity": "export import handelsbalans",
        "unique_scope": "inte kommunal handel",
        "geographic_scope": "Sverige",
    },
    "scb_hushall": {
        "description": "SCB-statistik om hushallsstorlek och boendeform.",
        "keywords": ["hushållsstorlek", "boendeform", "inkomst", "konsumtion"],
        "main_identifier": "SCB hushållsstatistik",
        "core_activity": "hushållsstorlek boendeform",
        "unique_scope": "inte kommunal bostadskö Kolada",
        "geographic_scope": "Sverige",
    },
    "scb_halsa_sjukvard": {
        "description": "SCB-statistik om sjukvard, dodsorsaker och halsa.",
        "keywords": ["sjukvård", "dödsorsaker", "sjukfrånvaro", "hälsa", "patientnöjdhet"],
        "main_identifier": "SCB hälso sjukvårdsstatistik",
        "core_activity": "sjukvård dödsorsaker hälsa",
        "unique_scope": "inte kommunal vårdkostnad Kolada",
        "geographic_scope": "Sverige",
    },
    "scb_jordbruk": {
        "description": "SCB-statistik om jordbruk, areal och skord.",
        "keywords": ["jordbruk", "areal", "skörd", "djurhållning", "livsmedelsproduktion"],
        "main_identifier": "SCB jordbruksstatistik",
        "core_activity": "jordbruk areal skörd",
        "unique_scope": "inte kommunal miljö Kolada",
        "geographic_scope": "Sverige",
    },
    "scb_kultur": {
        "description": "SCB-statistik om idrott, fritid och turism.",
        "keywords": ["idrott", "fritid", "turism", "bibliotek", "museum", "evenemang", "deltagande"],
        "main_identifier": "SCB kulturstatistik",
        "core_activity": "idrott fritid turism",
        "unique_scope": "inte kommunal kulturhus Kolada",
        "geographic_scope": "Sverige",
    },
    "scb_levnadsforhallanden": {
        "description": "SCB-statistik om inkomst, fattigdom och levnadsforhallanden.",
        "keywords": ["inkomst", "fattigdom", "boende", "hälsa", "utbildning"],
        "main_identifier": "SCB levnadsförhållanden statistik",
        "core_activity": "inkomst fattigdom boende",
        "unique_scope": "inte kommunal IFO Kolada",
        "geographic_scope": "Sverige",
    },
    "scb_miljo": {
        "description": "SCB-statistik om utslapp, klimat och hallbarhet.",
        "keywords": ["utsläpp", "klimat", "hållbarhet", "energi", "avfall", "vatten", "luftkvalitet"],
        "main_identifier": "SCB miljöstatistik",
        "core_activity": "utsläpp klimat hållbarhet",
        "unique_scope": "inte kommunal återvinning Kolada",
        "geographic_scope": "Sverige",
    },
    "scb_nationalrakenskaper": {
        "description": "SCB nationalrakenskaper: BNP, konsumtion och investeringar.",
        "keywords": ["BNP", "konsumtion", "investeringar", "export", "import", "tillväxt"],
        "main_identifier": "SCB nationalräkenskaper",
        "core_activity": "BNP konsumtion investeringar",
        "unique_scope": "inte kommunal ekonomi Kolada",
        "geographic_scope": "Sverige",
    },
    "scb_naringsverksamhet": {
        "description": "SCB-statistik om foretag, omsattning och anstallda per bransch.",
        "keywords": ["företag", "omsättning", "anställda", "bransch", "nyföretagande"],
        "main_identifier": "SCB näringsverksamhet statistik",
        "core_activity": "företag omsättning anställda",
        "unique_scope": "inte kommunal sysselsättning Kolada",
        "geographic_scope": "Sverige",
    },
    "scb_offentlig_ekonomi": {
        "description": "SCB-statistik om kommunal och statlig ekonomi, skatter och bidrag.",
        "keywords": ["kommun", "stat", "skatter", "bidrag", "utgifter"],
        "main_identifier": "SCB offentlig ekonomi statistik",
        "core_activity": "kommun stat skatter",
        "unique_scope": "inte kommunal budget Kolada",
        "geographic_scope": "Sverige",
    },
    "scb_priser_konsumtion": {
        "description": "SCB-statistik om KPI, inflation och konsumtionspriser.",
        "keywords": ["KPI", "inflation", "konsumtionsprisindex", "livsmedelspriser"],
        "main_identifier": "SCB priser konsumtion statistik",
        "core_activity": "KPI inflation konsumtionsprisindex",
        "unique_scope": "inte kommunal skattesats Kolada",
        "geographic_scope": "Sverige",
    },
    "scb_socialtjanst": {
        "description": "SCB-statistik om ekonomiskt bistand och socialtjanst.",
        "keywords": ["ekonomiskt", "bistånd", "familjehem", "missbruk", "LVU", "försörjningsstöd"],
        "main_identifier": "SCB socialtjänst statistik",
        "core_activity": "ekonomiskt bistånd familjehem",
        "unique_scope": "inte kommunal IFO Kolada",
        "geographic_scope": "Sverige",
    },
    "scb_transporter": {
        "description": "SCB-statistik om vag-, jarnvags-, flyg- och sjotransporter.",
        "keywords": ["väg", "järnväg", "flyg", "sjöfart", "persontrafik", "godstransport"],
        "main_identifier": "SCB transportstatistik",
        "core_activity": "väg järnväg flyg",
        "unique_scope": "inte realtids trafik Trafikverket",
        "geographic_scope": "Sverige",
    },
    "scb_utbildning": {
        "description": "SCB-statistik om skolresultat, elever och examina.",
        "keywords": ["skolresultat", "elever", "studenter", "examen", "gymnasium", "högskola"],
        "main_identifier": "SCB utbildningsstatistik",
        "core_activity": "skolresultat elever examen",
        "unique_scope": "inte kommunal pedagogtäthet Kolada",
        "geographic_scope": "Sverige",
    },
    "scb_amnesovergripande": {
        "description": "SCB tvarvetenskaplig statistik och amnesovergripande nyckeltal.",
        "keywords": ["tvärvetenskaplig", "nyckeltal", "jämförelser", "kommun", "region"],
        "main_identifier": "SCB ämnesövergripande statistik",
        "core_activity": "tvärvetenskaplig nyckeltal",
        "unique_scope": "catch-all när ingen specifik kategori passar",
        "geographic_scope": "Sverige",
    },
    "scb_befolkning_folkmangd": {
        "description": "SCB-data om antal invanare och folkmangd per region, kommun, alder och kon.",
        "keywords": ["antal", "invånare", "folkmängd", "per", "region", "kommun", "ålder", "kön"],
        "main_identifier": "SCB befolkningsfolkmängd",
        "core_activity": "antal invånare folkmängd",
        "unique_scope": "inte flyttningar födelser dödsfall",
        "geographic_scope": "kommun Sverige",
    },
    "scb_befolkning_forandringar": {
        "description": "SCB-data om flyttningar, migration och befolkningsforandringar.",
        "keywords": ["flyttningar", "inrikes", "utrikes", "migration", "nettoflytt", "tidsserie"],
        "main_identifier": "SCB befolkningsförändringar",
        "core_activity": "flyttningar migration",
        "unique_scope": "inte statisk folkmängd",
        "geographic_scope": "Sverige",
    },
    "scb_befolkning_fodda": {
        "description": "SCB-data om fodelsetal, nativitet och fertilitet.",
        "keywords": ["födda", "barn", "nativitet", "fertilitet", "TFR", "födelser", "per", "region", "kön"],
        "main_identifier": "SCB födelsetal",
        "core_activity": "födda barn nativitet",
        "unique_scope": "inte dödsfall eller flyttningar",
        "geographic_scope": "Sverige",
    },
    "scb_arbetsmarknad_arbetsloshet": {
        "description": "SCB-data om arbetsloshet och arbetsloshetgrad per bransch och alder.",
        "keywords": ["arbetslöshet", "arbetslöshetsgrad", "AKU", "tidsserie", "bransch", "ålder", "kön"],
        "main_identifier": "SCB arbetslöshetsstatistik",
        "core_activity": "arbetslöshet arbetslöshetsgrad",
        "unique_scope": "inte sysselsättning eller löner",
        "geographic_scope": "Sverige",
    },
    "scb_arbetsmarknad_sysselsattning": {
        "description": "SCB-data om sysselsattning och sysselsattningsgrad.",
        "keywords": ["sysselsättning", "sysselsättningsgrad", "arbetskraft", "deltagande", "bransch"],
        "main_identifier": "SCB sysselsättningsstatistik",
        "core_activity": "sysselsättning sysselsättningsgrad",
        "unique_scope": "inte arbetslöshet eller löner",
        "geographic_scope": "Sverige",
    },
    "scb_arbetsmarknad_lon": {
        "description": "SCB-data om loner, medellon och loneutveckling per bransch och yrke.",
        "keywords": ["löner", "medellön", "medianlön", "löneutveckling", "inkomstskillnad", "kön", "bransch", "yrke"],
        "main_identifier": "SCB lönestatistik",
        "core_activity": "löner medellön medianlön",
        "unique_scope": "inte sysselsättning eller arbetslöshet",
        "geographic_scope": "Sverige",
    },
    "scb_boende_bygglov": {
        "description": "SCB-data om bygglov, beviljade ansokningar och byggstarter.",
        "keywords": ["bygglov", "beviljade", "ansökningar", "byggstart", "nybyggnation"],
        "main_identifier": "SCB bygglov statistik",
        "core_activity": "bygglov beviljade ansökningar",
        "unique_scope": "inte befintligt bostadsbestånd",
        "geographic_scope": "Sverige",
    },
    "scb_boende_nybyggnation": {
        "description": "SCB-data om nybyggda bostader och bostadsproduktion.",
        "keywords": ["nybyggda", "bostäder", "byggstart", "färdigställt", "bostadsproduktion"],
        "main_identifier": "SCB nybyggnation statistik",
        "core_activity": "nybyggda bostäder byggstart",
        "unique_scope": "inte befintligt bostadsbestånd",
        "geographic_scope": "Sverige",
    },
    "scb_boende_bestand": {
        "description": "SCB-data om bostadsbestand: antal bostader, smahus och flerbostadshus.",
        "keywords": ["antal", "bostäder", "småhus", "flerbostadshus", "hyresrätt", "bostadsrätt", "byggår"],
        "main_identifier": "SCB bostadsbestånd statistik",
        "core_activity": "antal bostäder småhus flerbostadshus",
        "unique_scope": "inte nybyggnation eller bygglov",
        "geographic_scope": "Sverige",
    },
    "smhi_vaderprognoser": {
        "description": "SMHI vaderprognoser: temperatur, nederbord och vind for svenska orter.",
        "keywords": ["prognos", "temperatur", "nederbörd", "vind", "moln", "regn", "snö", "timprognos", "dygnsprognos", "AROME", "MEPS"],
        "main_identifier": "SMHI väderprognoser",
        "core_activity": "prognos temperatur nederbörd vind",
        "unique_scope": "inte aktuella observationer eller vägväder",
        "geographic_scope": "Sverige",
    },
    "smhi_vaderanalyser": {
        "description": "SMHI vaderanalyser med MESAN-griddata for molntackning och stralning.",
        "keywords": ["analys", "MESAN", "grid", "molntäckning", "strålning", "vindriktning", "temperatur", "analyserad", "data"],
        "main_identifier": "SMHI väderanalyser",
        "core_activity": "analys MESAN grid",
        "unique_scope": "inte råobservationer eller prognoser",
        "geographic_scope": "Sverige",
    },
    "smhi_vaderobservationer": {
        "description": "SMHI realtidsmatningar av temperatur, nederbord och vind fran stationer.",
        "keywords": ["realtidsmätningar", "temperatur", "nederbörd", "vind", "lufttryck", "luftfuktighet", "sikt", "stationer"],
        "main_identifier": "SMHI väderobservationer",
        "core_activity": "realtidsmätningar temperatur nederbörd",
        "unique_scope": "inte prognoser eller analyser",
        "geographic_scope": "Sverige",
    },
    "smhi_hydrologi": {
        "description": "SMHI hydrologiska data: vattenfloden och vattennivaer i svenska vattendrag.",
        "keywords": ["vattenflöde", "vattennivå", "avrinningsområde", "hydrologi", "mätstationer", "realtid", "prognoser"],
        "main_identifier": "SMHI hydrologi",
        "core_activity": "vattenflöden vattennivåer",
        "unique_scope": "inte havsvågor eller brandrisk",
        "geographic_scope": "Sverige",
    },
    "smhi_oceanografi": {
        "description": "SMHI oceanografiska data: havsvagor, vaghojd och strommar.",
        "keywords": ["havsvågor", "våghöjd", "strömmar", "havsnivåer", "bojar", "kustdata", "observationer", "prognoser"],
        "main_identifier": "SMHI oceanografi",
        "core_activity": "havsvågor våghöjd strömmar",
        "unique_scope": "inte sjöar eller hydrologi",
        "geographic_scope": "Sverige",
    },
    "smhi_brandrisk": {
        "description": "SMHI brandriskindex (FWI, FFMC, ISI) for skogsbrand.",
        "keywords": ["brandrisk", "FWI", "FFMC", "ISI", "vindpåverkan", "skogsbrandindex", "prognos"],
        "main_identifier": "SMHI brandrisk",
        "core_activity": "brandriskindex FWI FFMC ISI",
        "unique_scope": "inte allmän väderprognos eller observationer",
        "geographic_scope": "Sverige",
    },
    "smhi_weather": {
        "description": "SMHI vaderprognoser (legacy-alias for METFCST).",
        "keywords": ["prognos", "temperatur", "nederbörd", "vind", "moln", "regn", "snö", "timprognos", "dygnsprognos", "AROME"],
        "main_identifier": "SMHI väderprognoser legacy",
        "core_activity": "prognos temperatur nederbörd vind",
        "unique_scope": "legacy alias för METFCST prognoser",
        "geographic_scope": "Sverige",
    },
    "smhi_vaderprognoser_metfcst": {
        "description": "SMHI vaderprognoser via METFCST-modellen.",
        "keywords": ["prognos", "temperatur", "nederbörd", "vind", "moln", "regn", "snö", "timprognos", "dygnsprognos", "AROME", "MEPS"],
        "main_identifier": "SMHI väderprognoser METFCST",
        "core_activity": "prognos temperatur nederbörd vind",
        "unique_scope": "inte snöspecifik prognos eller analyser",
        "geographic_scope": "Sverige",
    },
    "smhi_vaderprognoser_snow1g": {
        "description": "SMHI snoprognoser via SNOW1G-modellen.",
        "keywords": ["snödjup", "snöfall", "snötäcke", "vinterprognos", "snörelaterad", "prognos"],
        "main_identifier": "SMHI snöprognoser SNOW1G",
        "core_activity": "snödjup snöfall snötäcke",
        "unique_scope": "inte allmän väderprognos",
        "geographic_scope": "Sverige",
    },
    "smhi_vaderanalyser_mesan2g": {
        "description": "SMHI vaderanalyser via MESAN2G-griddata.",
        "keywords": ["analys", "MESAN", "grid", "molntäckning", "strålning", "vindriktning", "temperatur", "analyserad", "data"],
        "main_identifier": "SMHI väderanalyser MESAN2G",
        "core_activity": "analys molntäckning strålning",
        "unique_scope": "inte råobservationer eller prognoser",
        "geographic_scope": "Sverige",
    },
    "smhi_vaderobservationer_metobs": {
        "description": "SMHI vaderobservationer via METOBS-stationer.",
        "keywords": ["realtidsmätningar", "temperatur", "nederbörd", "vind", "lufttryck", "luftfuktighet", "sikt", "stationer"],
        "main_identifier": "SMHI väderobservationer METOBS",
        "core_activity": "realtidsmätningar temperatur nederbörd",
        "unique_scope": "inte prognoser eller analyser",
        "geographic_scope": "Sverige",
    },
    "smhi_hydrologi_hydroobs": {
        "description": "SMHI hydrologiska realtidsobservationer via HYDROOBS.",
        "keywords": ["vattenflöde", "vattennivå", "avrinningsområde", "realtidsmätningar", "stationer"],
        "main_identifier": "SMHI hydrologi observationer HYDROOBS",
        "core_activity": "vattenflöde vattennivå realtid",
        "unique_scope": "inte prognoser",
        "geographic_scope": "Sverige",
    },
    "smhi_hydrologi_pthbv": {
        "description": "SMHI hydrologiska prognoser via PTHBV-modellen.",
        "keywords": ["prognos", "vattenflöde", "vattennivå", "översvämning", "avrinningsområde"],
        "main_identifier": "SMHI hydrologi prognoser PTHBV",
        "core_activity": "prognos vattenflöde vattennivå",
        "unique_scope": "inte observationer",
        "geographic_scope": "Sverige",
    },
    "smhi_oceanografi_ocobs": {
        "description": "SMHI oceanografiska realtidsobservationer via OCOBS.",
        "keywords": ["havsvågor", "våghöjd", "strömmar", "havsnivåer", "bojar", "kustdata", "realtid"],
        "main_identifier": "SMHI oceanografi observationer OCOBS",
        "core_activity": "havsvågor våghöjd strömmar realtid",
        "unique_scope": "inte prognoser",
        "geographic_scope": "Sverige",
    },
    "smhi_brandrisk_fwif": {
        "description": "SMHI brandriskprognos via FWIF-modellen.",
        "keywords": ["brandrisk", "FWI", "FFMC", "ISI", "vindpåverkan", "skogsbrandprognos"],
        "main_identifier": "SMHI brandrisk prognos FWIF",
        "core_activity": "brandriskindex FWI FFMC ISI prognos",
        "unique_scope": "inte allmän väderprognos",
        "geographic_scope": "Sverige",
    },
    "smhi_brandrisk_fwia": {
        "description": "SMHI brandriskanalys via FWIA-modellen.",
        "keywords": ["brandriskanalys", "FWI", "FFMC", "ISI", "vindpåverkan", "skogsbrandindex"],
        "main_identifier": "SMHI brandrisk analys FWIA",
        "core_activity": "brandriskanalys FWI FFMC ISI",
        "unique_scope": "inte prognos eller observationer",
        "geographic_scope": "Sverige",
    },
    "trafikverket_trafikinfo": {
        "description": "Trafikverkets realtidsdata om storningar, olyckor och koer pa vagar.",
        "keywords": ["störningar", "olyckor", "köer", "vägavstängningar", "trafikinfo", "realtid", "E4", "E20", "vägtrafik"],
        "main_identifier": "Trafikverket trafikinfo",
        "core_activity": "störningar olyckor köer vägavstängningar",
        "unique_scope": "inte tågförseningar eller kamerabilder",
        "geographic_scope": "Sverige väg",
    },
    "trafikverket_tag": {
        "description": "Trafikverkets data om tagtrafik, forseningar och tidtabeller.",
        "keywords": ["tågtrafik", "förseningar", "tidtabell", "stationer", "inställda", "tåg", "SJ", "pendeltåg", "järnväg"],
        "main_identifier": "Trafikverket tåg",
        "core_activity": "tågtrafik förseningar tidtabell stationer",
        "unique_scope": "inte vägtrafik eller kameror",
        "geographic_scope": "Sverige tåg",
    },
    "trafikverket_vag": {
        "description": "Trafikverkets data om vagstatus, underhall och hastighetsbegransningar.",
        "keywords": ["vägstatus", "underhåll", "hastighet", "avstängningar", "vägtrafik", "E4", "E20", "realtid", "VViS"],
        "main_identifier": "Trafikverket väg",
        "core_activity": "vägstatus underhåll hastighet avstängningar",
        "unique_scope": "inte tåg eller kameror",
        "geographic_scope": "Sverige väg",
    },
    "trafikverket_vader": {
        "description": "Trafikverkets vagvaderdata: halka, vind och temperatur pa vagar.",
        "keywords": ["vägväder", "halka", "vind", "temperatur", "snö", "is", "väglag", "VViS", "realtid", "väg"],
        "main_identifier": "Trafikverket väder",
        "core_activity": "vägväder halka vind temperatur",
        "unique_scope": "inte allmän SMHI-väder eller prognos",
        "geographic_scope": "Sverige väg",
    },
    "trafikverket_kameror": {
        "description": "Trafikverkets trafikbilder och kameror langs vagnatet.",
        "keywords": ["trafikbilder", "kameror", "snapshot", "lista", "status", "realtid", "E4", "E20", "vägtrafik"],
        "main_identifier": "Trafikverket kameror",
        "core_activity": "trafikbilder snapshot lista status",
        "unique_scope": "inte vägstatus eller tåg",
        "geographic_scope": "Sverige väg",
    },
    "trafikverket_prognos": {
        "description": "Trafikverkets prognoser for vag- och tagtrafik.",
        "keywords": ["trafikprognos", "vägprognos", "tågprognos", "förseningar", "framtid", "trafikinfo"],
        "main_identifier": "Trafikverket prognos",
        "core_activity": "trafikprognos väg tåg",
        "unique_scope": "inte realtidsdata eller observationer",
        "geographic_scope": "Sverige",
    },
    "trafikverket_trafikinfo_storningar": {
        "description": "Realtidsdata om trafikstorningar pa vagar.",
        "keywords": ["störningar", "olyckor", "köer", "trafikinfo", "realtid", "E4", "E20", "vägtrafik"],
        "main_identifier": "Trafikverket trafikinfo störningar",
        "core_activity": "störningar olyckor köer",
        "unique_scope": "inte tåg eller kameror",
        "geographic_scope": "Sverige väg",
    },
    "trafikverket_trafikinfo_olyckor": {
        "description": "Realtidsdata om trafikolyckor och incidenter.",
        "keywords": ["olyckor", "incidenter", "trafikinfo", "realtid", "E4", "E20", "vägtrafik"],
        "main_identifier": "Trafikverket trafikinfo olyckor",
        "core_activity": "olyckor incidenter",
        "unique_scope": "inte köer eller avstängningar",
        "geographic_scope": "Sverige väg",
    },
    "trafikverket_trafikinfo_koer": {
        "description": "Realtidsdata om koer och kobildning pa vagar.",
        "keywords": ["köer", "köbildning", "trafikinfo", "realtid", "E4", "E20", "vägtrafik"],
        "main_identifier": "Trafikverket trafikinfo köer",
        "core_activity": "köer köbildning",
        "unique_scope": "inte olyckor eller avstängningar",
        "geographic_scope": "Sverige väg",
    },
    "trafikverket_trafikinfo_vagarbeten": {
        "description": "Realtidsdata om vagavstangningar och vagarbeten.",
        "keywords": ["vägavstängningar", "vägavstängningar", "arbeten", "trafikinfo", "realtid", "E4", "E20"],
        "main_identifier": "Trafikverket trafikinfo vägavstängningar",
        "core_activity": "vägavstängningar arbeten",
        "unique_scope": "inte olyckor eller köer",
        "geographic_scope": "Sverige väg",
    },
    "trafikverket_tag_forseningar": {
        "description": "Data om tagforseningar i realtid.",
        "keywords": ["tågförseningar", "förseningar", "tågtrafik", "SJ", "pendeltåg", "järnväg"],
        "main_identifier": "Trafikverket tåg förseningar",
        "core_activity": "tågförseningar",
        "unique_scope": "inte inställda tåg eller tidtabell",
        "geographic_scope": "Sverige tåg",
    },
    "trafikverket_tag_tidtabell": {
        "description": "Tidtabeller for tagtrafik med avgangar och ankomster.",
        "keywords": ["tidtabell", "avgångar", "ankomster", "tågtrafik", "SJ", "pendeltåg", "järnväg"],
        "main_identifier": "Trafikverket tåg tidtabell",
        "core_activity": "tidtabell avgångar",
        "unique_scope": "inte förseningar eller inställda tåg",
        "geographic_scope": "Sverige tåg",
    },
    "trafikverket_tag_stationer": {
        "description": "Information om tagstationer i Sverige.",
        "keywords": ["stationer", "tågstationer", "tågtrafik", "SJ", "pendeltåg", "järnväg"],
        "main_identifier": "Trafikverket tåg stationer",
        "core_activity": "stationer tågstationer",
        "unique_scope": "inte tidtabell eller förseningar",
        "geographic_scope": "Sverige tåg",
    },
    "trafikverket_tag_installda": {
        "description": "Data om installda tag och avganger.",
        "keywords": ["inställda", "tåg", "inställda", "avgångar", "tågtrafik", "SJ", "pendeltåg", "järnväg"],
        "main_identifier": "Trafikverket tåg inställda",
        "core_activity": "inställda tåg",
        "unique_scope": "inte förseningar eller tidtabell",
        "geographic_scope": "Sverige tåg",
    },
    "trafikverket_vag_status": {
        "description": "Realtidsstatus for vagar i Sverige.",
        "keywords": ["vägstatus", "realtid", "vägtrafik", "E4", "E20", "VViS"],
        "main_identifier": "Trafikverket väg status",
        "core_activity": "vägstatus realtid",
        "unique_scope": "inte hastighet eller underhåll",
        "geographic_scope": "Sverige väg",
    },
    "trafikverket_vag_underhall": {
        "description": "Data om vagunderhall och pagaende arbeten.",
        "keywords": ["vägunderhåll", "vägtrafik", "E4", "E20", "realtid"],
        "main_identifier": "Trafikverket väg underhåll",
        "core_activity": "vägunderhåll",
        "unique_scope": "inte vägstatus eller hastighet",
        "geographic_scope": "Sverige väg",
    },
    "trafikverket_vag_hastighet": {
        "description": "Hastighetsbegransningar pa svenska vagar.",
        "keywords": ["hastighetsbegränsningar", "vägtrafik", "E4", "E20", "realtid"],
        "main_identifier": "Trafikverket väg hastighet",
        "core_activity": "hastighetsbegränsningar",
        "unique_scope": "inte vägstatus eller underhåll",
        "geographic_scope": "Sverige väg",
    },
    "trafikverket_vag_avstangningar": {
        "description": "Data om vagavstangningar.",
        "keywords": ["vägavstängningar", "vägtrafik", "E4", "E20", "realtid"],
        "main_identifier": "Trafikverket väg avstängningar",
        "core_activity": "vägavstängningar",
        "unique_scope": "inte olyckor eller köer",
        "geographic_scope": "Sverige väg",
    },
    "trafikverket_vader_stationer": {
        "description": "Vagvaderdata fran Trafikverkets matsstationer.",
        "keywords": ["vägväder", "stationer", "VViS", "temperatur", "vind", "snö", "is", "realtid"],
        "main_identifier": "Trafikverket vägväder stationer",
        "core_activity": "vägväder stationer",
        "unique_scope": "inte allmän SMHI-väder",
        "geographic_scope": "Sverige väg",
    },
    "trafikverket_vader_halka": {
        "description": "Halkriskdata fran Trafikverkets vagvaderstationer.",
        "keywords": ["halkrisk", "väglag", "snö", "is", "VViS", "realtid", "väg"],
        "main_identifier": "Trafikverket vägväder halka",
        "core_activity": "halkrisk",
        "unique_scope": "inte allmän temperatur eller vind",
        "geographic_scope": "Sverige väg",
    },
    "trafikverket_vader_vind": {
        "description": "Vindhastighet och vindriktning fran vagvaderstationer.",
        "keywords": ["vindhastighet", "vindriktning", "VViS", "realtid", "väg"],
        "main_identifier": "Trafikverket vägväder vind",
        "core_activity": "vindhastighet vindriktning",
        "unique_scope": "inte temperatur eller halkrisk",
        "geographic_scope": "Sverige väg",
    },
    "trafikverket_vader_temperatur": {
        "description": "Temperaturdata fran Trafikverkets vagvaderstationer.",
        "keywords": ["temperatur", "vägväder", "VViS", "realtid", "väg"],
        "main_identifier": "Trafikverket vägväder temperatur",
        "core_activity": "temperatur vägväder",
        "unique_scope": "inte vind eller halkrisk",
        "geographic_scope": "Sverige väg",
    },
    "trafikverket_kameror_lista": {
        "description": "Lista over Trafikverkets trafikkameror langs vagnatet.",
        "keywords": ["kameror", "lista", "stationer", "trafikbilder", "realtid", "E4", "E20"],
        "main_identifier": "Trafikverket kameror lista",
        "core_activity": "kameror lista stationer",
        "unique_scope": "inte snapshot eller status",
        "geographic_scope": "Sverige väg",
    },
    "trafikverket_kameror_snapshot": {
        "description": "Ogonblicksbilder fran Trafikverkets trafikkameror.",
        "keywords": ["kamerabilder", "snapshot", "trafikbilder", "realtid", "E4", "E20"],
        "main_identifier": "Trafikverket kameror snapshot",
        "core_activity": "kamerabilder ögonblicksbilder",
        "unique_scope": "inte lista eller status",
        "geographic_scope": "Sverige väg",
    },
    "trafikverket_kameror_status": {
        "description": "Status for Trafikverkets trafikkameror.",
        "keywords": ["kamerastatus", "trafikbilder", "realtid", "E4", "E20"],
        "main_identifier": "Trafikverket kameror status",
        "core_activity": "kamerastatus",
        "unique_scope": "inte snapshot eller lista",
        "geographic_scope": "Sverige väg",
    },
    "trafikverket_prognos_trafik": {
        "description": "Trafikprognoser for vag- och tagtrafik.",
        "keywords": ["trafikprognos", "vägprognos", "förseningar", "framtid", "trafikinfo"],
        "main_identifier": "Trafikverket trafikprognos",
        "core_activity": "trafikprognos",
        "unique_scope": "inte realtidsdata",
        "geographic_scope": "Sverige",
    },
    "trafikverket_prognos_vag": {
        "description": "Vagprognoser for framtida trafikforhallanden.",
        "keywords": ["vägprognos", "trafikprognos", "framtid", "vägtrafik", "E4", "E20"],
        "main_identifier": "Trafikverket vägprognos",
        "core_activity": "vägprognos",
        "unique_scope": "inte realtids vägstatus",
        "geographic_scope": "Sverige väg",
    },
    "trafikverket_prognos_tag": {
        "description": "Tagprognoser for framtida forseningar.",
        "keywords": ["tågprognos", "förseningar", "framtid", "tågtrafik", "SJ", "pendeltåg"],
        "main_identifier": "Trafikverket tågprognos",
        "core_activity": "tågprognos",
        "unique_scope": "inte realtids tågstatus",
        "geographic_scope": "Sverige tåg",
    },
    "riksdag_dokument": {
        "description": "Riksdagens dokument: propositioner, motioner och betankanden.",
        "keywords": ["propositioner", "motioner", "betänkanden", "interpellationer", "frågor", "protokoll", "SOU", "DS", "EU"],
        "main_identifier": "Riksdagen dokument",
        "core_activity": "propositioner motioner betänkanden",
        "unique_scope": "inte ledamöter eller voteringar",
        "geographic_scope": "Sverige riksdagen",
    },
    "riksdag_ledamoter": {
        "description": "Data om riksdagsledamoter, partier och valkretsar.",
        "keywords": ["riksdagsledamöter", "ledamöter", "parti", "valkrets", "riksdagsval", "mandatperiod", "namn"],
        "main_identifier": "Riksdagen ledamöter",
        "core_activity": "riksdagsledamöter partier valkretsar",
        "unique_scope": "inte dokument eller voteringar",
        "geographic_scope": "Sverige riksdagen",
    },
    "riksdag_voteringar": {
        "description": "Resultat fran riksdagens omrostningar och voteringar.",
        "keywords": ["voteringar", "omröstningar", "resultat", "ja", "nej", "avstämning", "riksdagsbeslut", "voteringar"],
        "main_identifier": "Riksdagen voteringar",
        "core_activity": "voteringar omröstningar resultat",
        "unique_scope": "inte dokument eller anföranden",
        "geographic_scope": "Sverige riksdagen",
    },
    "riksdag_anforanden": {
        "description": "Riksdagens anforanden fran debatter och fragestunder.",
        "keywords": ["anföranden", "tal", "debatt", "frågestund", "kammaren", "protokoll", "riksdagsdebatt"],
        "main_identifier": "Riksdagen anföranden",
        "core_activity": "tal debatt frågestund",
        "unique_scope": "inte voteringar eller dokument",
        "geographic_scope": "Sverige riksdagen",
    },
    "riksdag_dokumentstatus": {
        "description": "Status och behandlingshistorik for riksdagsdokument.",
        "keywords": ["dokumentstatus", "historik", "behandling", "riksdagsprocess", "riksdagsärende", "status"],
        "main_identifier": "Riksdagen dokumentstatus",
        "core_activity": "dokumentstatus historik behandling",
        "unique_scope": "inte själva dokumentinnehållet",
        "geographic_scope": "Sverige riksdagen",
    },
    "riksdag_dokument_proposition": {
        "description": "Regeringens propositioner till riksdagen.",
        "keywords": ["propositioner", "prop", "regeringsförslag", "propositioner", "riksdagsbeslut", "regering"],
        "main_identifier": "Riksdagen propositioner",
        "core_activity": "regeringsförslag propositioner",
        "unique_scope": "inte motioner eller betänkanden",
        "geographic_scope": "Sverige riksdagen",
    },
    "riksdag_dokument_motion": {
        "description": "Ledamoters motioner och forslag till riksdagen.",
        "keywords": ["motioner", "mot", "ledamöters", "förslag", "motioner", "riksdagsinitiativ"],
        "main_identifier": "Riksdagen motioner",
        "core_activity": "ledamöters förslag motioner",
        "unique_scope": "inte propositioner eller betänkanden",
        "geographic_scope": "Sverige riksdagen",
    },
    "riksdag_dokument_betankande": {
        "description": "Utskottsbetankanden fran riksdagens utskott.",
        "keywords": ["betänkanden", "bet", "utskottsbetänkanden", "kommittéer", "riksdagsutskott"],
        "main_identifier": "Riksdagen betänkanden",
        "core_activity": "utskottsbetänkanden kommittéer",
        "unique_scope": "inte propositioner eller motioner",
        "geographic_scope": "Sverige riksdagen",
    },
    "riksdag_dokument_interpellation": {
        "description": "Interpellationer och fragor till ministrar.",
        "keywords": ["interpellationer", "ip", "frågor", "till", "ministrar", "riksdagsdebatt"],
        "main_identifier": "Riksdagen interpellationer",
        "core_activity": "interpellationer frågestund",
        "unique_scope": "inte skriftliga frågor eller protokoll",
        "geographic_scope": "Sverige riksdagen",
    },
    "riksdag_dokument_fraga": {
        "description": "Skriftliga fragor fran riksdagsledamoter till ministrar.",
        "keywords": ["frågor", "fr", "skriftliga", "frågor", "riksdagsledamöter", "ministrar", "svar"],
        "main_identifier": "Riksdagen frågor",
        "core_activity": "skriftliga frågor fr",
        "unique_scope": "inte interpellationer eller protokoll",
        "geographic_scope": "Sverige riksdagen",
    },
    "riksdag_dokument_protokoll": {
        "description": "Kammarprotokoll och debattprotokoll fran riksdagen.",
        "keywords": ["protokoll", "kammarprotokoll", "debattprotokoll", "riksdagsmöten"],
        "main_identifier": "Riksdagen protokoll",
        "core_activity": "kammarprotokoll debattprotokoll",
        "unique_scope": "inte dokument eller voteringar",
        "geographic_scope": "Sverige riksdagen",
    },
    "riksdag_dokument_sou": {
        "description": "Statliga offentliga utredningar (SOU).",
        "keywords": ["SOU", "statliga", "utredningar", "offentliga", "utredningar", "riksdagsunderlag"],
        "main_identifier": "Riksdagen SOU utredningar",
        "core_activity": "statliga offentliga utredningar SOU",
        "unique_scope": "inte propositioner eller motioner",
        "geographic_scope": "Sverige riksdagen",
    },
    "riksdag_dokument_ds": {
        "description": "Departementspromemorior (DS) fran regeringen.",
        "keywords": ["DS", "departementspromemorior", "regeringsunderlag", "ministerier"],
        "main_identifier": "Riksdagen departementspromemorior",
        "core_activity": "departementspromemorior DS",
        "unique_scope": "inte SOU eller propositioner",
        "geographic_scope": "Sverige riksdagen",
    },
    "riksdag_dokument_dir": {
        "description": "Kommittedirektiv och utredningsdirektiv.",
        "keywords": ["direktiv", "kommittédirektiv", "utredningsdirektiv", "riksdagsuppdrag"],
        "main_identifier": "Riksdagen direktiv",
        "core_activity": "kommittédirektiv dir",
        "unique_scope": "inte SOU eller betänkanden",
        "geographic_scope": "Sverige riksdagen",
    },
    "riksdag_dokument_rskr": {
        "description": "Riksdagsskrivelser och formella riksdagsbeslut.",
        "keywords": ["rskr", "riksdagsskrivelser", "riksdagsbeslut", "skrivelser", "regering"],
        "main_identifier": "Riksdagen riksdagsskrivelser",
        "core_activity": "riksdagsskrivelser rskr",
        "unique_scope": "inte propositioner eller motioner",
        "geographic_scope": "Sverige riksdagen",
    },
    "riksdag_dokument_eu": {
        "description": "EU-dokument och EU-forslag som behandlas av riksdagen.",
        "keywords": ["EU-dokument", "KOM", "EU-förslag", "riksdagsbehandling", "EU-nämnden"],
        "main_identifier": "Riksdagen EU-dokument",
        "core_activity": "EU-förslag KOM EU-nämnden",
        "unique_scope": "inte nationella propositioner",
        "geographic_scope": "Sverige riksdagen",
    },
    "riksdag_dokument_rir": {
        "description": "Riksrevisionens granskningsrapporter (RIR).",
        "keywords": ["RIR", "Riksrevisionen", "rapporter", "granskning", "revision", "riksdagsunderlag"],
        "main_identifier": "Riksdagen RIR revisioner",
        "core_activity": "Riksrevisionens rapporter RIR",
        "unique_scope": "inte SOU eller propositioner",
        "geographic_scope": "Sverige riksdagen",
    },
    "riksdag_anforanden_debatt": {
        "description": "Debattanforanden fran riksdagens kammare.",
        "keywords": ["debatt", "tal", "allmän", "debatt", "budget", "utrikespolitik", "kammaren"],
        "main_identifier": "Riksdagen debattanföranden",
        "core_activity": "debatt tal allmän debatt",
        "unique_scope": "inte frågestund eller protokoll",
        "geographic_scope": "Sverige riksdagen",
    },
    "riksdag_anforanden_fragestund": {
        "description": "Anforanden fran riksdagens fragestunder.",
        "keywords": ["frågestund", "tal", "frågor", "ministrar", "riksdagsdebatt", "kammaren"],
        "main_identifier": "Riksdagen frågestund anföranden",
        "core_activity": "frågestund tal frågor ministrar",
        "unique_scope": "inte allmän debatt eller protokoll",
        "geographic_scope": "Sverige riksdagen",
    },
    "riksdag_ledamoter_parti": {
        "description": "Riksdagsledamoter sorterade per parti.",
        "keywords": ["ledamöter", "parti", "riksdagsledamöter", "mandatparti", "riksdagsval"],
        "main_identifier": "Riksdagen ledamöter parti",
        "core_activity": "ledamöter per parti",
        "unique_scope": "inte valkrets eller dokument",
        "geographic_scope": "Sverige riksdagen",
    },
    "riksdag_ledamoter_valkrets": {
        "description": "Riksdagsledamoter sorterade per valkrets.",
        "keywords": ["ledamöter", "valkrets", "riksdagsval", "valkretsmandat", "riksdagsledamöter"],
        "main_identifier": "Riksdagen ledamöter valkrets",
        "core_activity": "ledamöter per valkrets",
        "unique_scope": "inte parti eller dokument",
        "geographic_scope": "Sverige riksdagen",
    },
    "riksdag_voteringar_resultat": {
        "description": "Detaljerade resultat fran riksdagens voteringar.",
        "keywords": ["voteringar", "omröstningar", "resultat", "ja", "nej", "avstämning", "riksdagsbeslut"],
        "main_identifier": "Riksdagen voteringar resultat",
        "core_activity": "omröstningar resultat ja nej",
        "unique_scope": "inte dokument eller anföranden",
        "geographic_scope": "Sverige riksdagen",
    },
    "kolada_aldreomsorg": {
        "description": "Kolada nyckeltal for kommunal aldreomsorg: hemtjanst och sarskilt boende.",
        "keywords": ["hemtjänst", "särskilt", "boende", "timme", "brukare", "trygghetslarm", "valfrihet", "nöjdhet", "äldre", "vård"],
        "main_identifier": "Kolada äldreomsorg",
        "core_activity": "hemtjänst särskilt boende vård",
        "unique_scope": "inte sjukvård eller LSS",
        "geographic_scope": "kommun Sverige",
    },
    "kolada_arbetsmarknad": {
        "description": "Kolada nyckeltal for kommunal arbetsmarknad och sysselsattning.",
        "keywords": ["sysselsättning", "arbetslöshet", "åtgärder", "jobbcoachning", "etableringstid", "kommun"],
        "main_identifier": "Kolada arbetsmarknad",
        "core_activity": "sysselsättning arbetslöshet åtgärder",
        "unique_scope": "inte nationell SCB AKU eller löner",
        "geographic_scope": "kommun Sverige",
    },
    "kolada_barn_unga": {
        "description": "Kolada nyckeltal for barn- och ungdomsvard: placeringar och oppenvard.",
        "keywords": ["placeringar", "öppenvård", "insatser", "barn", "unga", "familjestöd", "LVU", "socialtjänst"],
        "main_identifier": "Kolada barn ungdomsvård",
        "core_activity": "placeringar öppenvård insatser",
        "unique_scope": "inte äldreomsorg eller skola",
        "geographic_scope": "kommun Sverige",
    },
    "kolada_boende": {
        "description": "Kolada nyckeltal for kommunalt boende: bostadsbestand och bostadsko.",
        "keywords": ["bostadsbestånd", "nybyggnation", "bostadskö", "hyror", "vakanser", "hyresnivå", "kommun"],
        "main_identifier": "Kolada boende bostäder",
        "core_activity": "bostadsbestånd nybyggnation bostadskö",
        "unique_scope": "inte nationell SCB byggstatistik",
        "geographic_scope": "kommun Sverige",
    },
    "kolada_demokrati": {
        "description": "Kolada nyckeltal for demokrati och medborgarservice i kommuner.",
        "keywords": ["valdeltagande", "medborgarengagemang", "förtroende", "e-tjänster", "medborgardialog"],
        "main_identifier": "Kolada demokrati medborgarservice",
        "core_activity": "valdeltagande engagemang förtroende",
        "unique_scope": "inte riksdagsvoteringar",
        "geographic_scope": "kommun Sverige",
    },
    "kolada_ekonomi": {
        "description": "Kolada nyckeltal for kommunal ekonomi: skattesats och kostnader.",
        "keywords": ["skattesats", "kostnader", "intäkter", "resultat", "balans", "budget", "skuldsättning", "investeringar"],
        "main_identifier": "Kolada kommunal ekonomi",
        "core_activity": "skattesats kostnader intäkter",
        "unique_scope": "inte nationell BNP SCB",
        "geographic_scope": "kommun Sverige",
    },
    "kolada_forskola": {
        "description": "Kolada nyckeltal for forskola: pedagogtathet och kostnader.",
        "keywords": ["barn", "pedagogtäthet", "kostnader", "kvalitetsindikator", "barn", "pedagog", "nöjdhet"],
        "main_identifier": "Kolada förskola",
        "core_activity": "barn pedagogtäthet kostnader",
        "unique_scope": "inte grundskola eller gymnasium",
        "geographic_scope": "kommun Sverige",
    },
    "kolada_grundskola": {
        "description": "Kolada nyckeltal for grundskola: larartathet och behorighet.",
        "keywords": ["elevantal", "lärartäthet", "behörighet", "betyg", "meritvärde", "kostnader", "lärare", "elev", "nöjdhet"],
        "main_identifier": "Kolada grundskola",
        "core_activity": "elevantal lärartäthet behörighet",
        "unique_scope": "inte förskola eller gymnasium",
        "geographic_scope": "kommun Sverige",
    },
    "kolada_gymnasieskola": {
        "description": "Kolada nyckeltal for gymnasieskola: genomstromning och examen.",
        "keywords": ["elevantal", "genomströmning", "examen", "behörighet", "meritpoäng", "kostnader", "avhopp"],
        "main_identifier": "Kolada gymnasieskola",
        "core_activity": "elevantal genomströmning examen",
        "unique_scope": "inte grundskola eller vuxenutbildning",
        "geographic_scope": "kommun Sverige",
    },
    "kolada_halsa": {
        "description": "Kolada nyckeltal for halso- och sjukvard i kommuner.",
        "keywords": ["vårdkostnader", "läkarbesök", "primärvård", "sjukhus", "väntetid", "patientnöjdhet", "DRG"],
        "main_identifier": "Kolada hälso sjukvård",
        "core_activity": "vårdkostnader läkarbesök primärvård",
        "unique_scope": "inte kommunal äldreomsorg eller LSS",
        "geographic_scope": "kommun Sverige",
    },
    "kolada_ifo": {
        "description": "Kolada nyckeltal for individ- och familjeomsorg (IFO).",
        "keywords": ["ekonomiskt", "bistånd", "familjehem", "missbruk", "öppenvård", "placeringar", "försörjningsstöd"],
        "main_identifier": "Kolada IFO individ familjeomsorg",
        "core_activity": "ekonomiskt bistånd familjehem missbruk",
        "unique_scope": "inte LSS eller äldreomsorg",
        "geographic_scope": "kommun Sverige",
    },
    "kolada_kultur": {
        "description": "Kolada nyckeltal for kultur och fritid i kommuner.",
        "keywords": ["bibliotek", "kulturhus", "fritidsverksamhet", "kulturkostnader", "besöksantal", "boklån", "nöjdhet"],
        "main_identifier": "Kolada kultur fritid",
        "core_activity": "bibliotek kulturhus fritidsverksamhet",
        "unique_scope": "inte nationell kulturstatistik SCB",
        "geographic_scope": "kommun Sverige",
    },
    "kolada_lss": {
        "description": "Kolada nyckeltal for LSS-insatser och funktionsnedsattning.",
        "keywords": ["personlig", "assistans", "boende", "särskild", "service", "LSS-insatser", "kostnad", "funktionsnedsättning"],
        "main_identifier": "Kolada LSS",
        "core_activity": "personlig assistans boende service",
        "unique_scope": "inte äldreomsorg eller sjukvård",
        "geographic_scope": "kommun Sverige",
    },
    "kolada_miljo": {
        "description": "Kolada nyckeltal for miljo och klimat i kommuner.",
        "keywords": ["avfall", "återvinning", "koldioxid", "energianvändning", "klimatpåverkan", "sophämtning", "utsortering"],
        "main_identifier": "Kolada miljö klimat",
        "core_activity": "avfall återvinning koldioxid",
        "unique_scope": "inte nationell SCB miljöstatistik",
        "geographic_scope": "kommun Sverige",
    },
    "kolada_sammanfattning": {
        "description": "Kolada allmannaversikt och sammanfattande nyckeltal.",
        "keywords": ["översikt", "kommunindex", "invånare", "ekonomi", "demografi", "miljö", "hälsa", "kultur", "förtroende"],
        "main_identifier": "Kolada allmänna nyckeltal",
        "core_activity": "översikt kommunindex invånare",
        "unique_scope": "catch-all när ingen specifik kategori passar",
        "geographic_scope": "kommun Sverige",
    },
    "kolada_aldreomsorg_hemtjanst": {
        "description": "Kolada nyckeltal for hemtjanst: timmar per brukare.",
        "keywords": ["hemtjänst", "timme", "per", "brukare", "trygghetslarm", "äldre", "vård", "omsorg"],
        "main_identifier": "Kolada äldreomsorg hemtjänst",
        "core_activity": "hemtjänst timmar brukare",
        "unique_scope": "inte särskilt boende eller LSS",
        "geographic_scope": "kommun Sverige",
    },
    "kolada_aldreomsorg_sarskiltboende": {
        "description": "Kolada nyckeltal for sarskilt boende i kommuner.",
        "keywords": ["särskilt", "boende", "vård", "omsorg", "äldre", "nöjdhet", "trygghetslarm"],
        "main_identifier": "Kolada äldreomsorg särskilt boende",
        "core_activity": "särskilt boende vård",
        "unique_scope": "inte hemtjänst eller sjukvård",
        "geographic_scope": "kommun Sverige",
    },
    "kolada_arbetsmarknad_arbetsloshet": {
        "description": "Kolada nyckeltal for arbetsloshet pa kommunniva.",
        "keywords": ["arbetslöshet", "kommun", "sysselsättning", "åtgärder", "jobbcoachning", "etableringstid"],
        "main_identifier": "Kolada arbetsmarknad arbetslöshet",
        "core_activity": "arbetslöshet kommun",
        "unique_scope": "inte nationell SCB AKU",
        "geographic_scope": "kommun Sverige",
    },
    "kolada_arbetsmarknad_etablering": {
        "description": "Kolada nyckeltal for etableringstid for nyanlanda.",
        "keywords": ["etableringstid", "nyanlända", "jobbcoachning", "åtgärder", "kommun"],
        "main_identifier": "Kolada arbetsmarknad etableringstid",
        "core_activity": "etableringstid nyanlända",
        "unique_scope": "inte nationell SCB sysselsättning",
        "geographic_scope": "kommun Sverige",
    },
    "kolada_forskola_pedagogtathet": {
        "description": "Kolada nyckeltal for pedagogtathet i forskola.",
        "keywords": ["barn", "pedagogtäthet", "barn", "per", "pedagog", "kostnader", "nöjdhet"],
        "main_identifier": "Kolada förskola pedagogtäthet",
        "core_activity": "barn pedagogtäthet",
        "unique_scope": "inte grundskola eller gymnasium",
        "geographic_scope": "kommun Sverige",
    },
    "kolada_forskola_kostnader": {
        "description": "Kolada nyckeltal for kostnader per barn i forskola.",
        "keywords": ["kostnader", "per", "barn", "pedagogtäthet", "nöjdhet", "förskoleverksamhet"],
        "main_identifier": "Kolada förskola kostnader",
        "core_activity": "kostnader per barn",
        "unique_scope": "inte antal barn eller kvalitet",
        "geographic_scope": "kommun Sverige",
    },
    "kolada_grundskola_meritvarde": {
        "description": "Kolada nyckeltal for meritvarden och betyg i arskurs 9.",
        "keywords": ["meritvärde", "betyg", "årskurs", "9", "lärartäthet", "behörighet", "kostnader"],
        "main_identifier": "Kolada grundskola meritvärde",
        "core_activity": "meritvärde betyg årskurs 9",
        "unique_scope": "inte förskola eller gymnasium",
        "geographic_scope": "kommun Sverige",
    },
    "kolada_grundskola_larartathet": {
        "description": "Kolada nyckeltal for larartathet i grundskola.",
        "keywords": ["lärartäthet", "behöriga", "lärare", "lärare", "per", "elev", "betyg", "kostnader"],
        "main_identifier": "Kolada grundskola lärartäthet",
        "core_activity": "lärartäthet behörighet",
        "unique_scope": "inte meritvärde eller nöjdhet",
        "geographic_scope": "kommun Sverige",
    },
}
