from __future__ import annotations

from app.agents.new_chat.tools.trafikverket_types import (
    TrafikverketCategory,
    TrafikverketFilterKind,
    TrafikverketToolDefinition,
    TrafikverketToolType,
)

TRAFIKVERKET_TOOL_DEFINITIONS: list[TrafikverketToolDefinition] = [
    TrafikverketToolDefinition(
        tool_id="trafikverket_auto",
        name="Trafikverket Auto",
        description=(
            "Automatisk trafikrouting som väljer rätt Trafikverket-verktyg "
            "för störningar, olyckor, tåg, vägarbeten, kameror och väder."
        ),
        keywords=[
            "trafikverket",
            "trafikinfo",
            "olycka",
            "störning",
            "kö",
            "vägarbete",
            "tåg",
            "avgång",
            "försening",
            "kamera",
            "väder",
            "prognos",
            "map",
        ],
        example_queries=[
            "Vad händer på E4 just nu?",
            "Finns det förseningar till Malmö C?",
            "Visa trafikkameror vid Slussen",
            "Vägarbeten på E18",
        ],
        base_path="/data.json",
        category=TrafikverketCategory.META,
        objecttype=None,
        schema_version=None,
        namespace=None,
        filter_kind=TrafikverketFilterKind.FREE,
        filter_fields=[],
        tool_type=TrafikverketToolType.AUTO,
        requires_filter=False,
    ),
    TrafikverketToolDefinition(
        tool_id="trafikverket_trafikinfo_storningar",
        name="Trafikverket Trafikinfo - Störningar",
        description="Allmänna störningar i väg- och järnvägstrafik (hinder, avbrott, incidenter).",
        keywords=[
            "störning",
            "störningar",
            "trafikstörning",
            "trafikinfo",
            "incident",
            "hinder",
            "avbrott",
            "signalproblem",
            "järnväg",
            "väg",
            "trafikverket",
        ],
        example_queries=[
            "Störningar på E4 vid Södertälje",
            "Trafikstörningar i Stockholm",
            "Störningar i tågtrafiken mellan Stockholm och Uppsala",
        ],
        base_path="/data.json",
        category=TrafikverketCategory.TRAFIKINFO,
        objecttype="Situation",
        schema_version="1.6",
        namespace="road.trafficinfo.new",
        filter_kind=TrafikverketFilterKind.LOCATION,
        filter_fields=["Deviation.LocationDescriptor", "Deviation.Message"],
        requires_filter=False,
        fallback_tool_ids=[
            "trafikverket_trafikinfo_olyckor",
            "trafikverket_trafikinfo_koer",
            "trafikverket_trafikinfo_vagarbeten",
        ],
    ),
    TrafikverketToolDefinition(
        tool_id="trafikverket_trafikinfo_olyckor",
        name="Trafikverket Trafikinfo - Olyckor",
        description="Olyckor och incidenter i trafiken (väg).",
        keywords=[
            "olycka",
            "trafikolycka",
            "krock",
            "incident",
            "singelolycka",
            "väg",
            "trafikinfo",
            "trafikverket",
        ],
        example_queries=[
            "Olycka på E6 vid Kungsbacka",
            "Trafikolyckor i Skåne idag",
            "Olycka på riksväg 40",
        ],
        base_path="/data.json",
        category=TrafikverketCategory.TRAFIKINFO,
        objecttype="Situation",
        schema_version="1.6",
        namespace="road.trafficinfo.new",
        filter_kind=TrafikverketFilterKind.LOCATION,
        filter_fields=["Deviation.LocationDescriptor", "Deviation.Message"],
        requires_filter=False,
        fallback_tool_ids=["trafikverket_trafikinfo_storningar"],
    ),
    TrafikverketToolDefinition(
        tool_id="trafikverket_trafikinfo_koer",
        name="Trafikverket Trafikinfo - Köer",
        description="Köer och framkomlighetsproblem på vägar.",
        keywords=[
            "kö",
            "köer",
            "koer",
            "trafikstockning",
            "trängsel",
            "framkomlighet",
            "trafikläge",
            "trafikinfo",
        ],
        example_queries=[
            "Var är det köer i Göteborg just nu?",
            "Köer på E18 mot Stockholm",
            "Trafikstockning på Essingeleden",
        ],
        base_path="/data.json",
        category=TrafikverketCategory.TRAFIKINFO,
        objecttype="Situation",
        schema_version="1.6",
        namespace="road.trafficinfo.new",
        filter_kind=TrafikverketFilterKind.LOCATION,
        filter_fields=["Deviation.LocationDescriptor", "Deviation.Message"],
        requires_filter=False,
        fallback_tool_ids=["trafikverket_trafikinfo_storningar"],
    ),
    TrafikverketToolDefinition(
        tool_id="trafikverket_trafikinfo_vagarbeten",
        name="Trafikverket Trafikinfo - Vägarbeten",
        description="Planerade och pågående vägarbeten samt omledningar.",
        keywords=[
            "vägarbete",
            "vägarbeten",
            "vagarbete",
            "arbete",
            "roadwork",
            "omledning",
            "avstängning",
            "trafikinfo",
        ],
        example_queries=[
            "Vägarbeten på E4 mot Helsingborg",
            "Pågående vägarbeten i Skåne län",
            "Vägarbete på riksväg 50",
        ],
        base_path="/data.json",
        category=TrafikverketCategory.TRAFIKINFO,
        objecttype="Situation",
        schema_version="1.6",
        namespace="road.trafficinfo.new",
        filter_kind=TrafikverketFilterKind.LOCATION,
        filter_fields=["Deviation.LocationDescriptor", "Deviation.Message"],
        requires_filter=False,
        fallback_tool_ids=["trafikverket_trafikinfo_storningar"],
    ),
    TrafikverketToolDefinition(
        tool_id="trafikverket_tag_forseningar",
        name="Trafikverket Tåg - Förseningar",
        description="Tågförseningar per station eller sträcka.",
        keywords=[
            "tåg",
            "tågförsening",
            "försening",
            "forsening",
            "försenad",
            "järnväg",
            "station",
            "spår",
        ],
        example_queries=[
            "Tågförseningar Stockholm C just nu",
            "Försenade tåg mot Göteborg",
            "Förseningar på Västra stambanan",
        ],
        base_path="/data.json",
        category=TrafikverketCategory.TAG,
        objecttype="TrainAnnouncement",
        schema_version="1.9",
        namespace="järnväg.trafikinfo",
        filter_kind=TrafikverketFilterKind.STATION,
        filter_fields=["AdvertisedLocationName"],
        requires_filter=False,
        fallback_tool_ids=["trafikverket_tag_tidtabell"],
    ),
    TrafikverketToolDefinition(
        tool_id="trafikverket_tag_tidtabell",
        name="Trafikverket Tåg - Tidtabell",
        description="Tidtabell för tågavgångar och ankomster.",
        keywords=[
            "tidtabell",
            "avgång",
            "ankomst",
            "tåg",
            "perrong",
            "spår",
            "schedule",
        ],
        example_queries=[
            "Avgångar från Malmö C",
            "Ankomster till Göteborg C",
            "Tidtabell Uppsala C imorgon",
        ],
        base_path="/data.json",
        category=TrafikverketCategory.TAG,
        objecttype="TrainAnnouncement",
        schema_version="1.9",
        namespace="järnväg.trafikinfo",
        filter_kind=TrafikverketFilterKind.STATION,
        filter_fields=["AdvertisedLocationName"],
        requires_filter=True,
        fallback_tool_ids=["trafikverket_tag_forseningar"],
    ),
    TrafikverketToolDefinition(
        tool_id="trafikverket_tag_stationer",
        name="Trafikverket Tåg - Stationer",
        description="Järnvägsstationer och hållplatser för tåg.",
        keywords=[
            "station",
            "stationer",
            "tågstation",
            "hållplats",
            "järnväg",
            "trafikverket",
        ],
        example_queries=[
            "Tågstationer i Uppsala län",
            "Stationer som börjar med 'Sundsvall'",
            "Lista stationer i Stockholm",
        ],
        base_path="/data.json",
        category=TrafikverketCategory.TAG,
        objecttype="TrainStation",
        schema_version="1.5",
        namespace="rail.infrastructure",
        filter_kind=TrafikverketFilterKind.STATION,
        filter_fields=["AdvertisedLocationName", "LocationSignature"],
        requires_filter=False,
    ),
    TrafikverketToolDefinition(
        tool_id="trafikverket_tag_installda",
        name="Trafikverket Tåg - Inställda",
        description="Inställda tåg per station eller sträcka.",
        keywords=["inställd", "inställda", "installd", "tåg", "avgång", "ankomst"],
        example_queries=[
            "Inställda tåg i Göteborg",
            "Inställda avgångar Stockholm C",
            "Inställda tåg mot Malmö",
        ],
        base_path="/data.json",
        category=TrafikverketCategory.TAG,
        objecttype="TrainAnnouncement",
        schema_version="1.9",
        namespace="järnväg.trafikinfo",
        filter_kind=TrafikverketFilterKind.STATION,
        filter_fields=["AdvertisedLocationName"],
        requires_filter=False,
        fallback_tool_ids=["trafikverket_tag_forseningar"],
    ),
    TrafikverketToolDefinition(
        tool_id="trafikverket_vag_status",
        name="Trafikverket Väg - Status",
        description="Trafikflöde och vägstatus för vägsträckor eller regioner.",
        keywords=[
            "vägstatus",
            "vagstatus",
            "trafikläge",
            "trafikflöde",
            "framkomlighet",
            "väg",
            "status",
        ],
        example_queries=[
            "Trafikläge på E4 vid Stockholm",
            "Vägstatus i Västra Götaland",
            "Framkomlighet på Essingeleden",
        ],
        base_path="/data.json",
        category=TrafikverketCategory.VAG,
        objecttype="TrafficFlow",
        schema_version="1.5",
        namespace="road.trafficinfo",
        filter_kind=TrafikverketFilterKind.ROAD,
        filter_fields=["RoadNumber"],
        requires_filter=False,
    ),
    TrafikverketToolDefinition(
        tool_id="trafikverket_vag_underhall",
        name="Trafikverket Väg - Underhåll",
        description="Underhållsinformation och vägskick för vägar.",
        keywords=[
            "underhåll",
            "underhall",
            "vägskick",
            "beläggning",
            "väg",
            "reparation",
        ],
        example_queries=[
            "Planerat underhåll på E18",
            "Underhållsarbeten i Skåne",
            "Vägskick på riksväg 70",
        ],
        base_path="/data.json",
        category=TrafikverketCategory.VAG,
        objecttype="RoadCondition",
        schema_version="1.3",
        namespace="road.trafficinfo",
        filter_kind=TrafikverketFilterKind.ROAD,
        filter_fields=["RoadNumber"],
        requires_filter=False,
    ),
    TrafikverketToolDefinition(
        tool_id="trafikverket_vag_hastighet",
        name="Trafikverket Väg - Hastighet",
        description="Gällande hastighetsgränser (inklusive temporära).",
        keywords=[
            "hastighet",
            "hastighetsgräns",
            "fartgräns",
            "begränsning",
            "speed",
            "väg",
        ],
        example_queries=[
            "Hastighetsgräns på E6",
            "Tillfälliga hastigheter på E4",
            "Fartgräns i Stockholm innerstad",
        ],
        base_path="/data.json",
        category=TrafikverketCategory.VAG,
        objecttype="Hastighetsgräns",
        schema_version="1.4",
        namespace="vägdata.nvdb_dk_o",
        filter_kind=TrafikverketFilterKind.ROAD,
        filter_fields=["RoadNumber"],
        requires_filter=False,
    ),
    TrafikverketToolDefinition(
        tool_id="trafikverket_vag_avstangningar",
        name="Trafikverket Väg - Avstängningar",
        description="Vägavstängningar, avspärrningar och omledningar.",
        keywords=[
            "avstängning",
            "avstängningar",
            "avstangning",
            "omledning",
            "avspärrning",
            "väg",
            "trafik",
        ],
        example_queries=[
            "Avstängningar på E20",
            "Omledning vid väg 73",
            "Vägavstängning i Uppsala",
        ],
        base_path="/data.json",
        category=TrafikverketCategory.VAG,
        objecttype="RoadCondition",
        schema_version="1.3",
        namespace="road.trafficinfo",
        filter_kind=TrafikverketFilterKind.ROAD,
        filter_fields=["RoadNumber"],
        requires_filter=False,
    ),
    TrafikverketToolDefinition(
        tool_id="trafikverket_vader_stationer",
        name="Trafikverket Väder - Stationer",
        description="Väderstationer och mätpunkter kopplade till trafiknät.",
        keywords=[
            "väderstation",
            "vaderstation",
            "station",
            "mätpunkt",
            "väderdata",
            "väglag",
            "väder",
        ],
        example_queries=[
            "Väderstationer i Norrbotten",
            "Mätstationer längs E4",
            "Vägväderstationer i Skåne",
        ],
        base_path="/data.json",
        category=TrafikverketCategory.VADER,
        objecttype="WeatherMeasurepoint",
        schema_version="2.1",
        namespace="road.weatherinfo",
        filter_kind=TrafikverketFilterKind.LOCATION,
        filter_fields=["Name", "LocationDescriptor"],
        requires_filter=False,
    ),
    TrafikverketToolDefinition(
        tool_id="trafikverket_vader_halka",
        name="Trafikverket Väder - Halka",
        description="Halka, isrisk och väglag kopplat till väder.",
        keywords=[
            "halka",
            "is",
            "isrisk",
            "väglag",
            "snö",
            "vader",
            "väder",
        ],
        example_queries=[
            "Risk för halka i Västerbotten",
            "Väglag på E45",
            "Halkvarning i Dalarna",
        ],
        base_path="/data.json",
        category=TrafikverketCategory.VADER,
        objecttype="WeatherObservation",
        schema_version="2.1",
        namespace="road.weatherinfo",
        filter_kind=TrafikverketFilterKind.LOCATION,
        filter_fields=["Name", "LocationDescriptor"],
        requires_filter=False,
    ),
    TrafikverketToolDefinition(
        tool_id="trafikverket_vader_vind",
        name="Trafikverket Väder - Vind",
        description="Vindinformation och vindbyar för trafikleder.",
        keywords=["vind", "vindstyrka", "vindby", "blåst", "storm", "vader", "väder"],
        example_queries=[
            "Vind på Öresundsbron",
            "Vindstyrka vid Högakustenbron",
            "Blåst i Skåne",
        ],
        base_path="/data.json",
        category=TrafikverketCategory.VADER,
        objecttype="WeatherObservation",
        schema_version="2.1",
        namespace="road.weatherinfo",
        filter_kind=TrafikverketFilterKind.LOCATION,
        filter_fields=["Name", "LocationDescriptor"],
        requires_filter=False,
    ),
    TrafikverketToolDefinition(
        tool_id="trafikverket_vader_temperatur",
        name="Trafikverket Väder - Temperatur",
        description="Temperaturer från väderstationer vid vägnätet.",
        keywords=["temperatur", "grader", "minus", "kall", "varm", "vader", "väder"],
        example_queries=[
            "Temperatur på E4 idag",
            "Temperaturer i Dalarna",
            "Minusgrader i Norrbotten",
        ],
        base_path="/data.json",
        category=TrafikverketCategory.VADER,
        objecttype="WeatherObservation",
        schema_version="2.1",
        namespace="road.weatherinfo",
        filter_kind=TrafikverketFilterKind.LOCATION,
        filter_fields=["Name", "LocationDescriptor"],
        requires_filter=False,
    ),
    TrafikverketToolDefinition(
        tool_id="trafikverket_kameror_lista",
        name="Trafikverket Kameror - Lista",
        description="Lista trafikkameror per region, plats eller väg.",
        keywords=[
            "kamera",
            "trafikkamera",
            "kameror",
            "livekamera",
            "bild",
            "snapshot",
            "väg",
        ],
        example_queries=[
            "Visa trafikkameror i Stockholm",
            "Kameror längs E4",
            "Lista kameror vid Essingeleden",
        ],
        base_path="/data.json",
        category=TrafikverketCategory.KAMEROR,
        objecttype="Camera",
        schema_version="1.1",
        namespace="road.infrastructure",
        filter_kind=TrafikverketFilterKind.LOCATION,
        filter_fields=["RoadNumber", "LocationDescriptor", "Name"],
        requires_filter=False,
    ),
    TrafikverketToolDefinition(
        tool_id="trafikverket_kameror_snapshot",
        name="Trafikverket Kameror - Snapshot",
        description="Hämta senaste bild/snapshot från en trafikkamera.",
        keywords=["kamera", "snapshot", "livebild", "senaste bild", "bild", "trafikkamera"],
        example_queries=[
            "Snapshot för kamera 12345",
            "Senaste bild från kamera E6-01",
            "Livebild kamera vid Slussen",
        ],
        base_path="/data.json",
        category=TrafikverketCategory.KAMEROR,
        objecttype="Camera",
        schema_version="1.1",
        namespace="road.infrastructure",
        filter_kind=TrafikverketFilterKind.CAMERA,
        filter_fields=["CameraId", "Id"],
        requires_filter=True,
    ),
    TrafikverketToolDefinition(
        tool_id="trafikverket_kameror_status",
        name="Trafikverket Kameror - Status",
        description="Status för trafikkamera (online/offline/drift).",
        keywords=["kamera", "status", "online", "offline", "drift", "tillgänglig"],
        example_queries=[
            "Status för kamera 12345",
            "Är kamera E4-10 online?",
            "Driftstatus trafikkamera vid E6",
        ],
        base_path="/data.json",
        category=TrafikverketCategory.KAMEROR,
        objecttype="Camera",
        schema_version="1.1",
        namespace="road.infrastructure",
        filter_kind=TrafikverketFilterKind.CAMERA,
        filter_fields=["CameraId", "Id"],
        requires_filter=True,
    ),
    TrafikverketToolDefinition(
        tool_id="trafikverket_prognos_trafik",
        name="Trafikverket Prognos - Trafik",
        description="Trafikprognoser per region/väg (belastning/restider).",
        keywords=["prognos", "trafik", "framtid", "belastning", "restid", "kö"],
        example_queries=[
            "Trafikprognos för E4 nästa vecka",
            "Prognos för trafik i Stockholm",
            "Restidsprognos på E6",
        ],
        base_path="/data.json",
        category=TrafikverketCategory.PROGNOS,
        objecttype="TravelTimeRoute",
        schema_version="1.6",
        namespace="road.trafficinfo",
        filter_kind=TrafikverketFilterKind.LOCATION,
        filter_fields=["RoadNumber", "LocationDescriptor"],
        requires_filter=False,
    ),
    TrafikverketToolDefinition(
        tool_id="trafikverket_prognos_vag",
        name="Trafikverket Prognos - Väg",
        description="Vägprognoser och planerade arbeten.",
        keywords=[
            "vägprognos",
            "prognos",
            "väg",
            "vag",
            "planerade arbeten",
            "planering",
        ],
        example_queries=[
            "Vägprognos E18",
            "Planerade arbeten kommande vecka",
            "Vägprojekt i Skåne län",
        ],
        base_path="/data.json",
        category=TrafikverketCategory.PROGNOS,
        objecttype="TravelTimeRoute",
        schema_version="1.6",
        namespace="road.trafficinfo",
        filter_kind=TrafikverketFilterKind.LOCATION,
        filter_fields=["RoadNumber", "LocationDescriptor"],
        requires_filter=False,
    ),
    TrafikverketToolDefinition(
        tool_id="trafikverket_prognos_tag",
        name="Trafikverket Prognos - Tåg",
        description="Tågprognoser och förväntade förseningar/positioner.",
        keywords=[
            "tågprognos",
            "prognos",
            "tåg",
            "försening",
            "forsening",
            "tågposition",
            "järnväg",
        ],
        example_queries=[
            "Tågprognos Stockholm C",
            "Förväntade förseningar till Göteborg",
            "Var är tåg 12345 nu?",
        ],
        base_path="/data.json",
        category=TrafikverketCategory.PROGNOS,
        objecttype="TrainPosition",
        schema_version="1.1",
        namespace="järnväg.trafikinfo",
        filter_kind=TrafikverketFilterKind.STATION,
        filter_fields=["AdvertisedLocationName"],
        requires_filter=False,
    ),
]

TRAFIKVERKET_TOOL_DEFINITION_MAP = {
    definition.tool_id: definition for definition in TRAFIKVERKET_TOOL_DEFINITIONS
}
